document.write(`
  <a id="SpellInfo:CalcCastTime" class="fn" href="../SpellInfo/CalcCastTime.html">CalcCastTime</a>
  <a id="SpellInfo:CanBeUsedInCombat" class="fn" href="../SpellInfo/CanBeUsedInCombat.html">CanBeUsedInCombat</a>
  <a id="SpellInfo:CanDispelAura" class="fn" href="../SpellInfo/CanDispelAura.html">CanDispelAura</a>
  <a id="SpellInfo:CanPierceImmuneAura" class="fn" href="../SpellInfo/CanPierceImmuneAura.html">CanPierceImmuneAura</a>
  <a id="SpellInfo:CanSpellProvideImmunityAgainstAura" class="fn" href="../SpellInfo/CanSpellProvideImmunityAgainstAura.html">CanSpellProvideImmunityAgainstAura</a>
  <a id="SpellInfo:CheckTarget" class="fn" href="../SpellInfo/CheckTarget.html">CheckTarget</a>
  <a id="SpellInfo:CheckTargetCreatureType" class="fn" href="../SpellInfo/CheckTargetCreatureType.html">CheckTargetCreatureType</a>
  <a id="SpellInfo:EffectIsAreaAuraEffect" class="fn" href="../SpellInfo/EffectIsAreaAuraEffect.html">EffectIsAreaAuraEffect</a>
  <a id="SpellInfo:EffectIsAura" class="fn" href="../SpellInfo/EffectIsAura.html">EffectIsAura</a>
  <a id="SpellInfo:EffectIsAuraType" class="fn" href="../SpellInfo/EffectIsAuraType.html">EffectIsAuraType</a>
  <a id="SpellInfo:EffectIsEffect" class="fn" href="../SpellInfo/EffectIsEffect.html">EffectIsEffect</a>
  <a id="SpellInfo:EffectIsEffectType" class="fn" href="../SpellInfo/EffectIsEffectType.html">EffectIsEffectType</a>
  <a id="SpellInfo:EffectIsTargetingArea" class="fn" href="../SpellInfo/EffectIsTargetingArea.html">EffectIsTargetingArea</a>
  <a id="SpellInfo:EffectIsUnitOwnedAuraEffect" class="fn" href="../SpellInfo/EffectIsUnitOwnedAuraEffect.html">EffectIsUnitOwnedAuraEffect</a>
  <a id="SpellInfo:GetActiveIconID" class="fn" href="../SpellInfo/GetActiveIconID.html">GetActiveIconID</a>
  <a id="SpellInfo:GetAllEffectsMechanicMask" class="fn" href="../SpellInfo/GetAllEffectsMechanicMask.html">GetAllEffectsMechanicMask</a>
  <a id="SpellInfo:GetAllowedMechanicMask" class="fn" href="../SpellInfo/GetAllowedMechanicMask.html">GetAllowedMechanicMask</a>
  <a id="SpellInfo:GetAreaGroupId" class="fn" href="../SpellInfo/GetAreaGroupId.html">GetAreaGroupId</a>
  <a id="SpellInfo:GetAttackType" class="fn" href="../SpellInfo/GetAttackType.html">GetAttackType</a>
  <a id="SpellInfo:GetAttributes" class="fn" href="../SpellInfo/GetAttributes.html">GetAttributes</a>
  <a id="SpellInfo:GetAttributesCu" class="fn" href="../SpellInfo/GetAttributesCu.html">GetAttributesCu</a>
  <a id="SpellInfo:GetAttributesEx" class="fn" href="../SpellInfo/GetAttributesEx.html">GetAttributesEx</a>
  <a id="SpellInfo:GetAttributesEx2" class="fn" href="../SpellInfo/GetAttributesEx2.html">GetAttributesEx2</a>
  <a id="SpellInfo:GetAttributesEx3" class="fn" href="../SpellInfo/GetAttributesEx3.html">GetAttributesEx3</a>
  <a id="SpellInfo:GetAttributesEx4" class="fn" href="../SpellInfo/GetAttributesEx4.html">GetAttributesEx4</a>
  <a id="SpellInfo:GetAttributesEx5" class="fn" href="../SpellInfo/GetAttributesEx5.html">GetAttributesEx5</a>
  <a id="SpellInfo:GetAttributesEx6" class="fn" href="../SpellInfo/GetAttributesEx6.html">GetAttributesEx6</a>
  <a id="SpellInfo:GetAttributesEx7" class="fn" href="../SpellInfo/GetAttributesEx7.html">GetAttributesEx7</a>
  <a id="SpellInfo:GetAuraInterruptFlags" class="fn" href="../SpellInfo/GetAuraInterruptFlags.html">GetAuraInterruptFlags</a>
  <a id="SpellInfo:GetAuraState" class="fn" href="../SpellInfo/GetAuraState.html">GetAuraState</a>
  <a id="SpellInfo:GetBaseLevel" class="fn" href="../SpellInfo/GetBaseLevel.html">GetBaseLevel</a>
  <a id="SpellInfo:GetCasterAuraSpell" class="fn" href="../SpellInfo/GetCasterAuraSpell.html">GetCasterAuraSpell</a>
  <a id="SpellInfo:GetCasterAuraState" class="fn" href="../SpellInfo/GetCasterAuraState.html">GetCasterAuraState</a>
  <a id="SpellInfo:GetCasterAuraStateNot" class="fn" href="../SpellInfo/GetCasterAuraStateNot.html">GetCasterAuraStateNot</a>
  <a id="SpellInfo:GetCategory" class="fn" href="../SpellInfo/GetCategory.html">GetCategory</a>
  <a id="SpellInfo:GetCategoryRecoveryTime" class="fn" href="../SpellInfo/GetCategoryRecoveryTime.html">GetCategoryRecoveryTime</a>
  <a id="SpellInfo:GetChannelInterruptFlags" class="fn" href="../SpellInfo/GetChannelInterruptFlags.html">GetChannelInterruptFlags</a>
  <a id="SpellInfo:GetDiminishingReturnsGroupForSpell" class="fn" href="../SpellInfo/GetDiminishingReturnsGroupForSpell.html">GetDiminishingReturnsGroupForSpell</a>
  <a id="SpellInfo:GetDiminishingReturnsGroupType" class="fn" href="../SpellInfo/GetDiminishingReturnsGroupType.html">GetDiminishingReturnsGroupType</a>
  <a id="SpellInfo:GetDiminishingReturnsLimitDuration" class="fn" href="../SpellInfo/GetDiminishingReturnsLimitDuration.html">GetDiminishingReturnsLimitDuration</a>
  <a id="SpellInfo:GetDiminishingReturnsMaxLevel" class="fn" href="../SpellInfo/GetDiminishingReturnsMaxLevel.html">GetDiminishingReturnsMaxLevel</a>
  <a id="SpellInfo:GetDispel" class="fn" href="../SpellInfo/GetDispel.html">GetDispel</a>
  <a id="SpellInfo:GetDmgClass" class="fn" href="../SpellInfo/GetDmgClass.html">GetDmgClass</a>
  <a id="SpellInfo:GetDuration" class="fn" href="../SpellInfo/GetDuration.html">GetDuration</a>
  <a id="SpellInfo:GetEffectAmplitude" class="fn" href="../SpellInfo/GetEffectAmplitude.html">GetEffectAmplitude</a>
  <a id="SpellInfo:GetEffectApplyAuraName" class="fn" href="../SpellInfo/GetEffectApplyAuraName.html">GetEffectApplyAuraName</a>
  <a id="SpellInfo:GetEffectBasePoints" class="fn" href="../SpellInfo/GetEffectBasePoints.html">GetEffectBasePoints</a>
  <a id="SpellInfo:GetEffectBonusMultiplier" class="fn" href="../SpellInfo/GetEffectBonusMultiplier.html">GetEffectBonusMultiplier</a>
  <a id="SpellInfo:GetEffectCalcRadius" class="fn" href="../SpellInfo/GetEffectCalcRadius.html">GetEffectCalcRadius</a>
  <a id="SpellInfo:GetEffectCalcValue" class="fn" href="../SpellInfo/GetEffectCalcValue.html">GetEffectCalcValue</a>
  <a id="SpellInfo:GetEffectChainTarget" class="fn" href="../SpellInfo/GetEffectChainTarget.html">GetEffectChainTarget</a>
  <a id="SpellInfo:GetEffectDamageMultiplier" class="fn" href="../SpellInfo/GetEffectDamageMultiplier.html">GetEffectDamageMultiplier</a>
  <a id="SpellInfo:GetEffectDieSides" class="fn" href="../SpellInfo/GetEffectDieSides.html">GetEffectDieSides</a>
  <a id="SpellInfo:GetEffectHasRadius" class="fn" href="../SpellInfo/GetEffectHasRadius.html">GetEffectHasRadius</a>
  <a id="SpellInfo:GetEffectImplicitTargetType" class="fn" href="../SpellInfo/GetEffectImplicitTargetType.html">GetEffectImplicitTargetType</a>
  <a id="SpellInfo:GetEffectIndex" class="fn" href="../SpellInfo/GetEffectIndex.html">GetEffectIndex</a>
  <a id="SpellInfo:GetEffectItemType" class="fn" href="../SpellInfo/GetEffectItemType.html">GetEffectItemType</a>
  <a id="SpellInfo:GetEffectMechanic" class="fn" href="../SpellInfo/GetEffectMechanic.html">GetEffectMechanic</a>
  <a id="SpellInfo:GetEffectMechanicMask" class="fn" href="../SpellInfo/GetEffectMechanicMask.html">GetEffectMechanicMask</a>
  <a id="SpellInfo:GetEffectMiscValue" class="fn" href="../SpellInfo/GetEffectMiscValue.html">GetEffectMiscValue</a>
  <a id="SpellInfo:GetEffectMiscValueB" class="fn" href="../SpellInfo/GetEffectMiscValueB.html">GetEffectMiscValueB</a>
  <a id="SpellInfo:GetEffectPointsPerComboPoint" class="fn" href="../SpellInfo/GetEffectPointsPerComboPoint.html">GetEffectPointsPerComboPoint</a>
  <a id="SpellInfo:GetEffectProvidedTargetMask" class="fn" href="../SpellInfo/GetEffectProvidedTargetMask.html">GetEffectProvidedTargetMask</a>
  <a id="SpellInfo:GetEffectRealPointsPerLevel" class="fn" href="../SpellInfo/GetEffectRealPointsPerLevel.html">GetEffectRealPointsPerLevel</a>
  <a id="SpellInfo:GetEffectSpellClassMask" class="fn" href="../SpellInfo/GetEffectSpellClassMask.html">GetEffectSpellClassMask</a>
  <a id="SpellInfo:GetEffectTargetACheckType" class="fn" href="../SpellInfo/GetEffectTargetACheckType.html">GetEffectTargetACheckType</a>
  <a id="SpellInfo:GetEffectTargetADirectionAngle" class="fn" href="../SpellInfo/GetEffectTargetADirectionAngle.html">GetEffectTargetADirectionAngle</a>
  <a id="SpellInfo:GetEffectTargetADirectionType" class="fn" href="../SpellInfo/GetEffectTargetADirectionType.html">GetEffectTargetADirectionType</a>
  <a id="SpellInfo:GetEffectTargetAIsArea" class="fn" href="../SpellInfo/GetEffectTargetAIsArea.html">GetEffectTargetAIsArea</a>
  <a id="SpellInfo:GetEffectTargetAObjectType" class="fn" href="../SpellInfo/GetEffectTargetAObjectType.html">GetEffectTargetAObjectType</a>
  <a id="SpellInfo:GetEffectTargetAReferenceType" class="fn" href="../SpellInfo/GetEffectTargetAReferenceType.html">GetEffectTargetAReferenceType</a>
  <a id="SpellInfo:GetEffectTargetASelectionCategory" class="fn" href="../SpellInfo/GetEffectTargetASelectionCategory.html">GetEffectTargetASelectionCategory</a>
  <a id="SpellInfo:GetEffectTargetATarget" class="fn" href="../SpellInfo/GetEffectTargetATarget.html">GetEffectTargetATarget</a>
  <a id="SpellInfo:GetEffectTargetBCheckType" class="fn" href="../SpellInfo/GetEffectTargetBCheckType.html">GetEffectTargetBCheckType</a>
  <a id="SpellInfo:GetEffectTargetBDirectionAngle" class="fn" href="../SpellInfo/GetEffectTargetBDirectionAngle.html">GetEffectTargetBDirectionAngle</a>
  <a id="SpellInfo:GetEffectTargetBDirectionType" class="fn" href="../SpellInfo/GetEffectTargetBDirectionType.html">GetEffectTargetBDirectionType</a>
  <a id="SpellInfo:GetEffectTargetBIsArea" class="fn" href="../SpellInfo/GetEffectTargetBIsArea.html">GetEffectTargetBIsArea</a>
  <a id="SpellInfo:GetEffectTargetBObjectType" class="fn" href="../SpellInfo/GetEffectTargetBObjectType.html">GetEffectTargetBObjectType</a>
  <a id="SpellInfo:GetEffectTargetBReferenceType" class="fn" href="../SpellInfo/GetEffectTargetBReferenceType.html">GetEffectTargetBReferenceType</a>
  <a id="SpellInfo:GetEffectTargetBSelectionCategory" class="fn" href="../SpellInfo/GetEffectTargetBSelectionCategory.html">GetEffectTargetBSelectionCategory</a>
  <a id="SpellInfo:GetEffectTargetBTarget" class="fn" href="../SpellInfo/GetEffectTargetBTarget.html">GetEffectTargetBTarget</a>
  <a id="SpellInfo:GetEffectTriggerSpell" class="fn" href="../SpellInfo/GetEffectTriggerSpell.html">GetEffectTriggerSpell</a>
  <a id="SpellInfo:GetEffectType" class="fn" href="../SpellInfo/GetEffectType.html">GetEffectType</a>
  <a id="SpellInfo:GetEffectUsedTargetObjectType" class="fn" href="../SpellInfo/GetEffectUsedTargetObjectType.html">GetEffectUsedTargetObjectType</a>
  <a id="SpellInfo:GetEffectValueMultiplier" class="fn" href="../SpellInfo/GetEffectValueMultiplier.html">GetEffectValueMultiplier</a>
  <a id="SpellInfo:GetEquippedItemClass" class="fn" href="../SpellInfo/GetEquippedItemClass.html">GetEquippedItemClass</a>
  <a id="SpellInfo:GetEquippedItemInventoryTypeMask" class="fn" href="../SpellInfo/GetEquippedItemInventoryTypeMask.html">GetEquippedItemInventoryTypeMask</a>
  <a id="SpellInfo:GetEquippedItemSubClassMask" class="fn" href="../SpellInfo/GetEquippedItemSubClassMask.html">GetEquippedItemSubClassMask</a>
  <a id="SpellInfo:GetExcludeCasterAuraSpell" class="fn" href="../SpellInfo/GetExcludeCasterAuraSpell.html">GetExcludeCasterAuraSpell</a>
  <a id="SpellInfo:GetExcludeTargetAuraSpell" class="fn" href="../SpellInfo/GetExcludeTargetAuraSpell.html">GetExcludeTargetAuraSpell</a>
  <a id="SpellInfo:GetExplicitTargetMask" class="fn" href="../SpellInfo/GetExplicitTargetMask.html">GetExplicitTargetMask</a>
  <a id="SpellInfo:GetFacingCasterFlags" class="fn" href="../SpellInfo/GetFacingCasterFlags.html">GetFacingCasterFlags</a>
  <a id="SpellInfo:GetId" class="fn" href="../SpellInfo/GetId.html">GetId</a>
  <a id="SpellInfo:GetInterruptFlags" class="fn" href="../SpellInfo/GetInterruptFlags.html">GetInterruptFlags</a>
  <a id="SpellInfo:GetManaCost" class="fn" href="../SpellInfo/GetManaCost.html">GetManaCost</a>
  <a id="SpellInfo:GetManaCostPercentage" class="fn" href="../SpellInfo/GetManaCostPercentage.html">GetManaCostPercentage</a>
  <a id="SpellInfo:GetManaCostPerlevel" class="fn" href="../SpellInfo/GetManaCostPerlevel.html">GetManaCostPerlevel</a>
  <a id="SpellInfo:GetManaPerSecond" class="fn" href="../SpellInfo/GetManaPerSecond.html">GetManaPerSecond</a>
  <a id="SpellInfo:GetManaPerSecondPerLevel" class="fn" href="../SpellInfo/GetManaPerSecondPerLevel.html">GetManaPerSecondPerLevel</a>
  <a id="SpellInfo:GetMaxAffectedTargets" class="fn" href="../SpellInfo/GetMaxAffectedTargets.html">GetMaxAffectedTargets</a>
  <a id="SpellInfo:GetMaxDuration" class="fn" href="../SpellInfo/GetMaxDuration.html">GetMaxDuration</a>
  <a id="SpellInfo:GetMaxLevel" class="fn" href="../SpellInfo/GetMaxLevel.html">GetMaxLevel</a>
  <a id="SpellInfo:GetMaxRange" class="fn" href="../SpellInfo/GetMaxRange.html">GetMaxRange</a>
  <a id="SpellInfo:GetMaxTargetLevel" class="fn" href="../SpellInfo/GetMaxTargetLevel.html">GetMaxTargetLevel</a>
  <a id="SpellInfo:GetMaxTicks" class="fn" href="../SpellInfo/GetMaxTicks.html">GetMaxTicks</a>
  <a id="SpellInfo:GetMechanic" class="fn" href="../SpellInfo/GetMechanic.html">GetMechanic</a>
  <a id="SpellInfo:GetMinRange" class="fn" href="../SpellInfo/GetMinRange.html">GetMinRange</a>
  <a id="SpellInfo:GetPowerType" class="fn" href="../SpellInfo/GetPowerType.html">GetPowerType</a>
  <a id="SpellInfo:GetPreventionType" class="fn" href="../SpellInfo/GetPreventionType.html">GetPreventionType</a>
  <a id="SpellInfo:GetPriority" class="fn" href="../SpellInfo/GetPriority.html">GetPriority</a>
  <a id="SpellInfo:GetProcChance" class="fn" href="../SpellInfo/GetProcChance.html">GetProcChance</a>
  <a id="SpellInfo:GetProcCharges" class="fn" href="../SpellInfo/GetProcCharges.html">GetProcCharges</a>
  <a id="SpellInfo:GetProcFlags" class="fn" href="../SpellInfo/GetProcFlags.html">GetProcFlags</a>
  <a id="SpellInfo:GetRank" class="fn" href="../SpellInfo/GetRank.html">GetRank</a>
  <a id="SpellInfo:GetReagent" class="fn" href="../SpellInfo/GetReagent.html">GetReagent</a>
  <a id="SpellInfo:GetReagentCount" class="fn" href="../SpellInfo/GetReagentCount.html">GetReagentCount</a>
  <a id="SpellInfo:GetRecoveryTime" class="fn" href="../SpellInfo/GetRecoveryTime.html">GetRecoveryTime</a>
  <a id="SpellInfo:GetRequiresSpellFocus" class="fn" href="../SpellInfo/GetRequiresSpellFocus.html">GetRequiresSpellFocus</a>
  <a id="SpellInfo:GetRuneCostID" class="fn" href="../SpellInfo/GetRuneCostID.html">GetRuneCostID</a>
  <a id="SpellInfo:GetSchoolMask" class="fn" href="../SpellInfo/GetSchoolMask.html">GetSchoolMask</a>
  <a id="SpellInfo:GetSpeed" class="fn" href="../SpellInfo/GetSpeed.html">GetSpeed</a>
  <a id="SpellInfo:GetSpellFamilyFlags" class="fn" href="../SpellInfo/GetSpellFamilyFlags.html">GetSpellFamilyFlags</a>
  <a id="SpellInfo:GetSpellFamilyName" class="fn" href="../SpellInfo/GetSpellFamilyName.html">GetSpellFamilyName</a>
  <a id="SpellInfo:GetSpellIconID" class="fn" href="../SpellInfo/GetSpellIconID.html">GetSpellIconID</a>
  <a id="SpellInfo:GetSpellLevel" class="fn" href="../SpellInfo/GetSpellLevel.html">GetSpellLevel</a>
  <a id="SpellInfo:GetSpellMechanicMaskByEffectMask" class="fn" href="../SpellInfo/GetSpellMechanicMaskByEffectMask.html">GetSpellMechanicMaskByEffectMask</a>
  <a id="SpellInfo:GetSpellSpecific" class="fn" href="../SpellInfo/GetSpellSpecific.html">GetSpellSpecific</a>
  <a id="SpellInfo:GetSpellVisual" class="fn" href="../SpellInfo/GetSpellVisual.html">GetSpellVisual</a>
  <a id="SpellInfo:GetStackAmount" class="fn" href="../SpellInfo/GetStackAmount.html">GetStackAmount</a>
  <a id="SpellInfo:GetStances" class="fn" href="../SpellInfo/GetStances.html">GetStances</a>
  <a id="SpellInfo:GetStancesNot" class="fn" href="../SpellInfo/GetStancesNot.html">GetStancesNot</a>
  <a id="SpellInfo:GetStartRecoveryCategory" class="fn" href="../SpellInfo/GetStartRecoveryCategory.html">GetStartRecoveryCategory</a>
  <a id="SpellInfo:GetStartRecoveryTime" class="fn" href="../SpellInfo/GetStartRecoveryTime.html">GetStartRecoveryTime</a>
  <a id="SpellInfo:GetTargetAuraSpell" class="fn" href="../SpellInfo/GetTargetAuraSpell.html">GetTargetAuraSpell</a>
  <a id="SpellInfo:GetTargetAuraState" class="fn" href="../SpellInfo/GetTargetAuraState.html">GetTargetAuraState</a>
  <a id="SpellInfo:GetTargetAuraStateNot" class="fn" href="../SpellInfo/GetTargetAuraStateNot.html">GetTargetAuraStateNot</a>
  <a id="SpellInfo:GetTargetCreatureType" class="fn" href="../SpellInfo/GetTargetCreatureType.html">GetTargetCreatureType</a>
  <a id="SpellInfo:GetTargets" class="fn" href="../SpellInfo/GetTargets.html">GetTargets</a>
  <a id="SpellInfo:GetTotem" class="fn" href="../SpellInfo/GetTotem.html">GetTotem</a>
  <a id="SpellInfo:GetTotemCategory" class="fn" href="../SpellInfo/GetTotemCategory.html">GetTotemCategory</a>
  <a id="SpellInfo:HasAreaAuraEffect" class="fn" href="../SpellInfo/HasAreaAuraEffect.html">HasAreaAuraEffect</a>
  <a id="SpellInfo:HasAura" class="fn" href="../SpellInfo/HasAura.html">HasAura</a>
  <a id="SpellInfo:HasEffect" class="fn" href="../SpellInfo/HasEffect.html">HasEffect</a>
  <a id="SpellInfo:HasInitialAggro" class="fn" href="../SpellInfo/HasInitialAggro.html">HasInitialAggro</a>
  <a id="SpellInfo:HasOnlyDamageEffects" class="fn" href="../SpellInfo/HasOnlyDamageEffects.html">HasOnlyDamageEffects</a>
  <a id="SpellInfo:IsAbilityLearnedWithProfession" class="fn" href="../SpellInfo/IsAbilityLearnedWithProfession.html">IsAbilityLearnedWithProfession</a>
  <a id="SpellInfo:IsAbilityOfSkillType" class="fn" href="../SpellInfo/IsAbilityOfSkillType.html">IsAbilityOfSkillType</a>
  <a id="SpellInfo:IsAffected" class="fn" href="../SpellInfo/IsAffected.html">IsAffected</a>
  <a id="SpellInfo:IsAffectedBySpellMod" class="fn" href="../SpellInfo/IsAffectedBySpellMod.html">IsAffectedBySpellMod</a>
  <a id="SpellInfo:IsAffectedBySpellMods" class="fn" href="../SpellInfo/IsAffectedBySpellMods.html">IsAffectedBySpellMods</a>
  <a id="SpellInfo:IsAffectingArea" class="fn" href="../SpellInfo/IsAffectingArea.html">IsAffectingArea</a>
  <a id="SpellInfo:IsAllowingDeadTarget" class="fn" href="../SpellInfo/IsAllowingDeadTarget.html">IsAllowingDeadTarget</a>
  <a id="SpellInfo:IsAuraExclusiveBySpecificPerCasterWith" class="fn" href="../SpellInfo/IsAuraExclusiveBySpecificPerCasterWith.html">IsAuraExclusiveBySpecificPerCasterWith</a>
  <a id="SpellInfo:IsAuraExclusiveBySpecificWith" class="fn" href="../SpellInfo/IsAuraExclusiveBySpecificWith.html">IsAuraExclusiveBySpecificWith</a>
  <a id="SpellInfo:IsAutoRepeatRangedSpell" class="fn" href="../SpellInfo/IsAutoRepeatRangedSpell.html">IsAutoRepeatRangedSpell</a>
  <a id="SpellInfo:IsAutocastable" class="fn" href="../SpellInfo/IsAutocastable.html">IsAutocastable</a>
  <a id="SpellInfo:IsBreakingStealth" class="fn" href="../SpellInfo/IsBreakingStealth.html">IsBreakingStealth</a>
  <a id="SpellInfo:IsChanneled" class="fn" href="../SpellInfo/IsChanneled.html">IsChanneled</a>
  <a id="SpellInfo:IsCooldownStartedOnEvent" class="fn" href="../SpellInfo/IsCooldownStartedOnEvent.html">IsCooldownStartedOnEvent</a>
  <a id="SpellInfo:IsDeathPersistent" class="fn" href="../SpellInfo/IsDeathPersistent.html">IsDeathPersistent</a>
  <a id="SpellInfo:IsDifferentRankOf" class="fn" href="../SpellInfo/IsDifferentRankOf.html">IsDifferentRankOf</a>
  <a id="SpellInfo:IsExplicitDiscovery" class="fn" href="../SpellInfo/IsExplicitDiscovery.html">IsExplicitDiscovery</a>
  <a id="SpellInfo:IsGroupBuff" class="fn" href="../SpellInfo/IsGroupBuff.html">IsGroupBuff</a>
  <a id="SpellInfo:IsHighRankOf" class="fn" href="../SpellInfo/IsHighRankOf.html">IsHighRankOf</a>
  <a id="SpellInfo:IsItemFitToSpellRequirements" class="fn" href="../SpellInfo/IsItemFitToSpellRequirements.html">IsItemFitToSpellRequirements</a>
  <a id="SpellInfo:IsLootCrafting" class="fn" href="../SpellInfo/IsLootCrafting.html">IsLootCrafting</a>
  <a id="SpellInfo:IsMoveAllowedChannel" class="fn" href="../SpellInfo/IsMoveAllowedChannel.html">IsMoveAllowedChannel</a>
  <a id="SpellInfo:IsMultiSlotAura" class="fn" href="../SpellInfo/IsMultiSlotAura.html">IsMultiSlotAura</a>
  <a id="SpellInfo:IsNextMeleeSwingSpell" class="fn" href="../SpellInfo/IsNextMeleeSwingSpell.html">IsNextMeleeSwingSpell</a>
  <a id="SpellInfo:IsPassive" class="fn" href="../SpellInfo/IsPassive.html">IsPassive</a>
  <a id="SpellInfo:IsPassiveStackableWithRanks" class="fn" href="../SpellInfo/IsPassiveStackableWithRanks.html">IsPassiveStackableWithRanks</a>
  <a id="SpellInfo:IsPositive" class="fn" href="../SpellInfo/IsPositive.html">IsPositive</a>
  <a id="SpellInfo:IsPositiveEffect" class="fn" href="../SpellInfo/IsPositiveEffect.html">IsPositiveEffect</a>
  <a id="SpellInfo:IsPrimaryProfession" class="fn" href="../SpellInfo/IsPrimaryProfession.html">IsPrimaryProfession</a>
  <a id="SpellInfo:IsPrimaryProfessionFirstRank" class="fn" href="../SpellInfo/IsPrimaryProfessionFirstRank.html">IsPrimaryProfessionFirstRank</a>
  <a id="SpellInfo:IsProfession" class="fn" href="../SpellInfo/IsProfession.html">IsProfession</a>
  <a id="SpellInfo:IsProfessionOrRiding" class="fn" href="../SpellInfo/IsProfessionOrRiding.html">IsProfessionOrRiding</a>
  <a id="SpellInfo:IsRangedWeaponSpell" class="fn" href="../SpellInfo/IsRangedWeaponSpell.html">IsRangedWeaponSpell</a>
  <a id="SpellInfo:IsRankOf" class="fn" href="../SpellInfo/IsRankOf.html">IsRankOf</a>
  <a id="SpellInfo:IsRanked" class="fn" href="../SpellInfo/IsRanked.html">IsRanked</a>
  <a id="SpellInfo:IsRequiringDeadTarget" class="fn" href="../SpellInfo/IsRequiringDeadTarget.html">IsRequiringDeadTarget</a>
  <a id="SpellInfo:IsSelfCast" class="fn" href="../SpellInfo/IsSelfCast.html">IsSelfCast</a>
  <a id="SpellInfo:IsSingleTarget" class="fn" href="../SpellInfo/IsSingleTarget.html">IsSingleTarget</a>
  <a id="SpellInfo:IsStackableOnOneSlotWithDifferentCasters" class="fn" href="../SpellInfo/IsStackableOnOneSlotWithDifferentCasters.html">IsStackableOnOneSlotWithDifferentCasters</a>
  <a id="SpellInfo:IsStackableWithRanks" class="fn" href="../SpellInfo/IsStackableWithRanks.html">IsStackableWithRanks</a>
  <a id="SpellInfo:IsTargetingArea" class="fn" href="../SpellInfo/IsTargetingArea.html">IsTargetingArea</a>
  <a id="SpellInfo:NeedsComboPoints" class="fn" href="../SpellInfo/NeedsComboPoints.html">NeedsComboPoints</a>
  <a id="SpellInfo:NeedsExplicitUnitTarget" class="fn" href="../SpellInfo/NeedsExplicitUnitTarget.html">NeedsExplicitUnitTarget</a>
  <a id="SpellInfo:NeedsToBeTriggeredByCaster" class="fn" href="../SpellInfo/NeedsToBeTriggeredByCaster.html">NeedsToBeTriggeredByCaster</a>
  <a id="SpellInfo:SpellCancelsAuraEffect" class="fn" href="../SpellInfo/SpellCancelsAuraEffect.html">SpellCancelsAuraEffect</a>
`);