var searchIndex = {};

searchIndex["Aura"] = {
    "items": [
        [0, "", "Aura", "The persistent effect of a <a class=\"mod\" href=\"Spell/index.html\">Spell</a> that remains on a <a class=\"mod\" href=\"Unit/index.html\">Unit</a> after the <a class=\"mod\" href=\"Spell/index.html\">Spell</a> has been cast."],
        [3, "GetAuraId", "", "Returns the ID of the <a class=\"mod\" href=\"Spell/index.html\">Spell</a> that caused this <a class=\"mod\" href=\"Aura/index.html\">Aura</a> to be applied."],
        [3, "GetCaster", "", "Returns the <a class=\"mod\" href=\"Unit/index.html\">Unit</a> that casted the <a class=\"mod\" href=\"Spell/index.html\">Spell</a> that caused this <a class=\"mod\" href=\"Aura/index.html\">Aura</a> to be applied."],
        [3, "GetCasterGUID", "", "Returns the GUID of the <a class=\"mod\" href=\"Unit/index.html\">Unit</a> that casted the <a class=\"mod\" href=\"Spell/index.html\">Spell</a> that caused this <a class=\"mod\" href=\"Aura/index.html\">Aura</a> to be applied."],
        [3, "GetCasterLevel", "", "Returns the level of the <a class=\"mod\" href=\"Unit/index.html\">Unit</a> that casted the <a class=\"mod\" href=\"Spell/index.html\">Spell</a> that caused this <a class=\"mod\" href=\"Aura/index.html\">Aura</a> to be applied."],
        [3, "GetDuration", "", "Returns the amount of time left until the <a class=\"mod\" href=\"Aura/index.html\">Aura</a> expires."],
        [3, "GetMaxDuration", "", "Returns the amount of time this <a class=\"mod\" href=\"Aura/index.html\">Aura</a> lasts when applied."],
        [3, "GetOwner", "", "Returns the <a class=\"mod\" href=\"Unit/index.html\">Unit</a> that the <a class=\"mod\" href=\"Aura/index.html\">Aura</a> has been applied to."],
        [3, "GetStackAmount", "", "Returns the number of times the <a class=\"mod\" href=\"Aura/index.html\">Aura</a> has &#34;stacked&#34;."],
        [3, "Remove", "", "Remove this <a class=\"mod\" href=\"Aura/index.html\">Aura</a> from the <a class=\"mod\" href=\"Unit/index.html\">Unit</a> it is applied to."],
        [3, "SetDuration", "", "Change the amount of time before the <a class=\"mod\" href=\"Aura/index.html\">Aura</a> expires."],
        [3, "SetMaxDuration", "", "Change the maximum amount of time before the <a class=\"mod\" href=\"Aura/index.html\">Aura</a> expires."],
        [3, "SetStackAmount", "", "Change the amount of times the <a class=\"mod\" href=\"Aura/index.html\">Aura</a> has &#34;stacked&#34; on the <a class=\"mod\" href=\"Unit/index.html\">Unit</a>."],
    ],
    "paths": []
};searchIndex["BattleGround"] = {
    "items": [
        [0, "", "BattleGround", ""],
        [3, "GetAlivePlayersCountByTeam", "", "Returns the amount of alive players in the [Battleground] by the team ID."],
        [3, "GetBonusHonorFromKillCount", "", "Returns the bonus honor given by amount of kills in the specific [Battleground]."],
        [3, "GetBracketId", "", "Returns the bracket ID of the specific [Battleground]."],
        [3, "GetEndTime", "", "Returns the end time of the [Battleground]."],
        [3, "GetFreeSlotsForTeam", "", "Returns the amount of free slots for the selected team in the specific [Battleground]."],
        [3, "GetInstanceId", "", "Returns the instance ID of the [Battleground]."],
        [3, "GetMap", "", "Returns the <a class=\"mod\" href=\"Map/index.html\">Map</a> of the [Battleground]."],
        [3, "GetMapId", "", "Returns the map ID of the [Battleground]."],
        [3, "GetMaxLevel", "", "Returns the max allowed <a class=\"mod\" href=\"Player/index.html\">Player</a> level of the specific [Battleground]."],
        [3, "GetMaxPlayers", "", "Returns the maximum allowed <a class=\"mod\" href=\"Player/index.html\">Player</a> count of the specific [Battleground]."],
        [3, "GetMaxPlayersPerTeam", "", "Returns the maximum allowed <a class=\"mod\" href=\"Player/index.html\">Player</a> count per team of the specific [Battleground]."],
        [3, "GetMinLevel", "", "Returns the minimum allowed <a class=\"mod\" href=\"Player/index.html\">Player</a> level of the specific [Battleground]."],
        [3, "GetMinPlayers", "", "Returns the minimum allowed <a class=\"mod\" href=\"Player/index.html\">Player</a> count of the specific [Battleground]."],
        [3, "GetMinPlayersPerTeam", "", "Returns the minimum allowed <a class=\"mod\" href=\"Player/index.html\">Player</a> count per team of the specific [Battleground]."],
        [3, "GetName", "", "Returns the name of the [Battleground]"],
        [3, "GetStatus", "", "Returns the status of the specific [Battleground]."],
        [3, "GetTypeId", "", "Returns the type ID of the [Battleground]."],
        [3, "GetWinner", "", "Returns the winning team of the specific [Battleground]."],
    ],
    "paths": []
};searchIndex["Corpse"] = {
    "items": [
        [0, "", "Corpse", ""],
        [3, "DeleteBonesFromWorld", "", "Deletes the <a class=\"mod\" href=\"Corpse/index.html\">Corpse</a> from the world."],
        [3, "GetGhostTime", "", "Returns the ghost time of a <a class=\"mod\" href=\"Corpse/index.html\">Corpse</a>."],
        [3, "GetOwnerGUID", "", "Returns the <a class=\"mod\" href=\"Corpse/index.html\">Corpse</a> Owner GUID."],
        [3, "GetType", "", "Returns the [CorpseType] of a <a class=\"mod\" href=\"Corpse/index.html\">Corpse</a>."],
        [3, "ResetGhostTime", "", "Resets the <a class=\"mod\" href=\"Corpse/index.html\">Corpse</a> ghost time."],
        [3, "SaveToDB", "", "Saves the <a class=\"mod\" href=\"Corpse/index.html\">Corpse</a> to the database."],
    ],
    "paths": []
};searchIndex["Creature"] = {
    "items": [
        [0, "", "Creature", "Non-<a class=\"mod\" href=\"Player/index.html\">Player</a> controlled <a class=\"mod\" href=\"Unit/index.html\">Unit</a>s."],
        [3, "AddLootMode", "", ""],
        [3, "AttackStart", "", "Make the <a class=\"mod\" href=\"Creature/index.html\">Creature</a> attack <code>target</code>."],
        [3, "CallAssistance", "", "Make the <a class=\"mod\" href=\"Creature/index.html\">Creature</a> call for assistance in combat from other nearby <a class=\"mod\" href=\"Creature/index.html\">Creature</a>s."],
        [3, "CallForHelp", "", "Make the <a class=\"mod\" href=\"Creature/index.html\">Creature</a> call for help in combat from friendly <a class=\"mod\" href=\"Creature/index.html\">Creature</a>s within <code>radius</code>."],
        [3, "CanAggro", "", "Returns <code>true</code> if the <a class=\"mod\" href=\"Creature/index.html\">Creature</a> can start attacking nearby hostile <a class=\"mod\" href=\"Unit/index.html\">Unit</a>s,   and returns <code>false</code> otherwise."],
        [3, "CanAssistTo", "", "Returns <code>true</code> if the <a class=\"mod\" href=\"Creature/index.html\">Creature</a> can assist <code>friend</code> in combat against <code>enemy</code>,   and returns <code>false</code> otherwise."],
        [3, "CanCompleteQuest", "", "Returns <code>true</code> if the <a class=\"mod\" href=\"Creature/index.html\">Creature</a> completes the <a class=\"mod\" href=\"Quest/index.html\">Quest</a> with the ID <code>questID</code>,   and returns <code>false</code> otherwise."],
        [3, "CanFly", "", "Returns <code>true</code> if the <a class=\"mod\" href=\"Creature/index.html\">Creature</a> can fly,   and returns <code>false</code> otherwise."],
        [3, "CanRegenerateHealth", "", "Returns <code>true</code> if the <a class=\"mod\" href=\"Creature/index.html\">Creature</a> can regenerate its health out-of-combat,   and returns <code>false</code> otherwise."],
        [3, "CanStartAttack", "", ""],
        [3, "CanSwim", "", "Returns <code>true</code> if the <a class=\"mod\" href=\"Creature/index.html\">Creature</a> can move through deep water,   and returns <code>false</code> otherwise."],
        [3, "CanWalk", "", "Returns <code>true</code> if the <a class=\"mod\" href=\"Creature/index.html\">Creature</a> can move on land,   and returns <code>false</code> otherwise."],
        [3, "DespawnOrUnsummon", "", "Despawn this <a class=\"mod\" href=\"Creature/index.html\">Creature</a>."],
        [3, "FleeToGetAssistance", "", "Make the <a class=\"mod\" href=\"Creature/index.html\">Creature</a> flee combat to get assistance from a nearby friendly <a class=\"mod\" href=\"Creature/index.html\">Creature</a>."],
        [3, "GetAIName", "", "Returns the <a class=\"mod\" href=\"Creature/index.html\">Creature</a>'s AI name."],
        [3, "GetAITarget", "", "Returns a target from the <a class=\"mod\" href=\"Creature/index.html\">Creature</a>'s threat list based on the   supplied arguments."],
        [3, "GetAITargets", "", "Returns all <a class=\"mod\" href=\"Unit/index.html\">Unit</a>s in the <a class=\"mod\" href=\"Creature/index.html\">Creature</a>'s threat list."],
        [3, "GetAITargetsCount", "", "Returns the number of <a class=\"mod\" href=\"Unit/index.html\">Unit</a>s in this <a class=\"mod\" href=\"Creature/index.html\">Creature</a>'s threat list."],
        [3, "GetAggroRange", "", "Returns the aggro range of the <a class=\"mod\" href=\"Creature/index.html\">Creature</a> for <code>target</code>."],
        [3, "GetAttackDistance", "", "Returns the effective aggro range of the <a class=\"mod\" href=\"Creature/index.html\">Creature</a> for <code>target</code>."],
        [3, "GetCorpseDelay", "", "Returns the delay between when the <a class=\"mod\" href=\"Creature/index.html\">Creature</a> dies and when its body despawns."],
        [3, "GetCreatureSpellCooldownDelay", "", "Returns the <a class=\"mod\" href=\"Creature/index.html\">Creature</a>'s cooldown for <code>spellID</code>."],
        [3, "GetCurrentWaypointId", "", "Returns the current waypoint ID of the <a class=\"mod\" href=\"Creature/index.html\">Creature</a>."],
        [3, "GetDefaultMovementType", "", "Returns the default movement type for this <a class=\"mod\" href=\"Creature/index.html\">Creature</a>."],
        [3, "GetHomePosition", "", "Returns position the <a class=\"mod\" href=\"Creature/index.html\">Creature</a> returns to when evading from combat   or respawning."],
        [3, "GetLootMode", "", ""],
        [3, "GetLootRecipient", "", "Returns the <a class=\"mod\" href=\"Player/index.html\">Player</a> that can loot this <a class=\"mod\" href=\"Creature/index.html\">Creature</a>."],
        [3, "GetLootRecipientGroup", "", "Returns the <a class=\"mod\" href=\"Group/index.html\">Group</a> that can loot this <a class=\"mod\" href=\"Creature/index.html\">Creature</a>."],
        [3, "GetNPCFlags", "", "Returns the <a class=\"mod\" href=\"Creature/index.html\">Creature</a>'s NPC flags."],
        [3, "GetRespawnDelay", "", "Returns the time it takes for this <a class=\"mod\" href=\"Creature/index.html\">Creature</a> to respawn once killed."],
        [3, "GetScriptId", "", "Returns the <a class=\"mod\" href=\"Creature/index.html\">Creature</a>'s script ID."],
        [3, "GetScriptName", "", "Returns the <a class=\"mod\" href=\"Creature/index.html\">Creature</a>'s script name."],
        [3, "GetShieldBlockValue", "", "Returns the <a class=\"mod\" href=\"Creature/index.html\">Creature</a>'s shield block value."],
        [3, "GetWanderRadius", "", "Returns the radius the <a class=\"mod\" href=\"Creature/index.html\">Creature</a> is permitted to wander from its   respawn point."],
        [3, "GetWaypointPath", "", "Returns the current waypoint path ID of the <a class=\"mod\" href=\"Creature/index.html\">Creature</a>."],
        [3, "HasCategoryCooldown", "", "Returns <code>true</code> if the <a class=\"mod\" href=\"Creature/index.html\">Creature</a> cannot cast <code>spellId</code> due to a category cooldown,   and returns <code>false</code> otherwise."],
        [3, "HasLootMode", "", ""],
        [3, "HasLootRecipient", "", "Returns <code>true</code> if the <a class=\"mod\" href=\"Creature/index.html\">Creature</a> will give its loot to a <a class=\"mod\" href=\"Player/index.html\">Player</a> or <a class=\"mod\" href=\"Group/index.html\">Group</a>,   and returns <code>false</code> otherwise."],
        [3, "HasQuest", "", "Returns <code>true</code> if the <a class=\"mod\" href=\"Creature/index.html\">Creature</a> starts the <a class=\"mod\" href=\"Quest/index.html\">Quest</a> <code>questId</code>,   and returns <code>false</code> otherwise."],
        [3, "HasSearchedAssistance", "", "Returns <code>true</code> if the <a class=\"mod\" href=\"Creature/index.html\">Creature</a> has searched for combat assistance already,   and returns <code>false</code> otherwise."],
        [3, "HasSpell", "", "Returns <code>true</code> if the <a class=\"mod\" href=\"Creature/index.html\">Creature</a> can cast <code>spellId</code> when mind-controlled,   and returns <code>false</code> otherwise."],
        [3, "HasSpellCooldown", "", "Returns <code>true</code> if the <a class=\"mod\" href=\"Creature/index.html\">Creature</a> has <code>spellId</code> on cooldown,   and returns <code>false</code> otherwise."],
        [3, "IsCivilian", "", "Returns <code>true</code> if the <a class=\"mod\" href=\"Creature/index.html\">Creature</a> is a civilian,   and returns <code>false</code> otherwise."],
        [3, "IsDamageEnoughForLootingAndReward", "", ""],
        [3, "IsElite", "", "Returns <code>true</code> if the <a class=\"mod\" href=\"Creature/index.html\">Creature</a>'s rank is Elite or Rare Elite,   and returns <code>false</code> otherwise."],
        [3, "IsGuard", "", "Returns <code>true</code> if the <a class=\"mod\" href=\"Creature/index.html\">Creature</a> is a city guard,   and returns <code>false</code> otherwise."],
        [3, "IsInEvadeMode", "", "Returns <code>true</code> if the <a class=\"mod\" href=\"Creature/index.html\">Creature</a> is returning to its spawn position from combat,   and returns <code>false</code> otherwise."],
        [3, "IsRacialLeader", "", "Returns <code>true</code> if the <a class=\"mod\" href=\"Creature/index.html\">Creature</a> is the leader of a player faction,   and returns <code>false</code> otherwise."],
        [3, "IsReputationGainDisabled", "", "Returns <code>true</code> if the <a class=\"mod\" href=\"Creature/index.html\">Creature</a> is set to not give reputation when killed,   and returns <code>false</code> otherwise."],
        [3, "IsTappedBy", "", "Returns <code>true</code> if the <a class=\"mod\" href=\"Creature/index.html\">Creature</a> will give its loot to <code>player</code>,   and returns <code>false</code> otherwise."],
        [3, "IsTargetableForAttack", "", "Returns <code>true</code> if the <a class=\"mod\" href=\"Creature/index.html\">Creature</a> can be targeted for attack,   and returns <code>false</code> otherwise."],
        [3, "IsTrigger", "", "Returns <code>true</code> if the <a class=\"mod\" href=\"Creature/index.html\">Creature</a> is an invisible trigger,   and returns <code>false</code> otherwise."],
        [3, "IsWorldBoss", "", "Returns <code>true</code> if the <a class=\"mod\" href=\"Creature/index.html\">Creature</a>'s rank is Boss,   and returns <code>false</code> otherwise."],
        [3, "MoveWaypoint", "", "Make the <a class=\"mod\" href=\"Creature/index.html\">Creature</a> start following it's waypoint path."],
        [3, "RemoveCorpse", "", "Remove this <a class=\"mod\" href=\"Creature/index.html\">Creature</a>'s corpse."],
        [3, "RemoveLootMode", "", ""],
        [3, "ResetLootMode", "", ""],
        [3, "Respawn", "", "Respawn this <a class=\"mod\" href=\"Creature/index.html\">Creature</a>."],
        [3, "SaveToDB", "", "Save the <a class=\"mod\" href=\"Creature/index.html\">Creature</a> in the database."],
        [3, "SelectVictim", "", "Make the <a class=\"mod\" href=\"Creature/index.html\">Creature</a> try to find a new target."],
        [3, "SetAggroEnabled", "", "Sets whether the <a class=\"mod\" href=\"Creature/index.html\">Creature</a> can be aggroed."],
        [3, "SetDeathState", "", "Sets the <a class=\"mod\" href=\"Creature/index.html\">Creature</a>'s death state to <code>deathState</code>."],
        [3, "SetDefaultMovementType", "", "Sets the default movement type of the <a class=\"mod\" href=\"Creature/index.html\">Creature</a>."],
        [3, "SetDisableGravity", "", "Makes the <a class=\"mod\" href=\"Creature/index.html\">Creature</a> able to fly if enabled."],
        [3, "SetDisableReputationGain", "", "Sets whether the <a class=\"mod\" href=\"Creature/index.html\">Creature</a> gives reputation or not."],
        [3, "SetEquipmentSlots", "", "Equips given <a class=\"mod\" href=\"Item/index.html\">Item</a>s to the <a class=\"mod\" href=\"Unit/index.html\">Unit</a>. Using 0 removes the equipped <a class=\"mod\" href=\"Item/index.html\">Item</a>"],
        [3, "SetHomePosition", "", "Sets the position the <a class=\"mod\" href=\"Creature/index.html\">Creature</a> returns to when evading from combat   or respawning."],
        [3, "SetHover", "", "Sets whether the creature is hovering / levitating or not."],
        [3, "SetInCombatWithZone", "", "Sets the <a class=\"mod\" href=\"Creature/index.html\">Creature</a> as in combat with all <a class=\"mod\" href=\"Player/index.html\">Player</a>s in the dungeon instance."],
        [3, "SetLootMode", "", ""],
        [3, "SetNPCFlags", "", "Sets the <a class=\"mod\" href=\"Creature/index.html\">Creature</a>'s NPC flags to <code>flags</code>."],
        [3, "SetNoCallAssistance", "", "Sets whether the <a class=\"mod\" href=\"Creature/index.html\">Creature</a> can call nearby enemies for help in combat or not."],
        [3, "SetNoSearchAssistance", "", "Sets whether the <a class=\"mod\" href=\"Creature/index.html\">Creature</a> can search for assistance at low health or not."],
        [3, "SetRespawnDelay", "", "Sets the time it takes for the <a class=\"mod\" href=\"Creature/index.html\">Creature</a> to respawn when killed."],
        [3, "SetWalk", "", "Sets whether the <a class=\"mod\" href=\"Creature/index.html\">Creature</a> is currently walking or running."],
        [3, "SetWanderRadius", "", "Sets the distance the <a class=\"mod\" href=\"Creature/index.html\">Creature</a> can wander from it's spawn point."],
        [3, "UpdateEntry", "", "Transform the <a class=\"mod\" href=\"Creature/index.html\">Creature</a> into another Creature."],
    ],
    "paths": []
};searchIndex["ElunaQuery"] = {
    "items": [
        [0, "", "ElunaQuery", ""],
        [3, "GetBool", "", ""],
        [3, "GetCString", "", ""],
        [3, "GetColumnCount", "", ""],
        [3, "GetDouble", "", ""],
        [3, "GetFloat", "", ""],
        [3, "GetInt16", "", ""],
        [3, "GetInt32", "", ""],
        [3, "GetInt64", "", ""],
        [3, "GetInt8", "", ""],
        [3, "GetRow", "", "Returns a table from the current row where keys are field names and values are the row's values. All numerical values will be numbers and everything else is returned as a string. For example <code>SELECT entry, name FROM creature_template</code> would result in a table of <code>{ entry = 123, name = &#34;some creature name&#34; }</code> To move to next row see <a class=\"fn\" href=\"ElunaQuery/NextRow.html\">ElunaQuery:NextRow</a>"],
        [3, "GetRowCount", "", ""],
        [3, "GetString", "", ""],
        [3, "GetUInt16", "", ""],
        [3, "GetUInt32", "", ""],
        [3, "GetUInt64", "", ""],
        [3, "GetUInt8", "", ""],
        [3, "IsNull", "", ""],
        [3, "NextRow", "", "Advances the ElunaQuery to the next row in the result returned. Returns false if there was no new row, otherwise true."],
    ],
    "paths": []
};searchIndex["GameObject"] = {
    "items": [
        [0, "", "GameObject", ""],
        [3, "Despawn", "", "Despawns a <a class=\"mod\" href=\"GameObject/index.html\">GameObject</a>"],
        [3, "GetDisplayId", "", "Returns display ID of the <a class=\"mod\" href=\"GameObject/index.html\">GameObject</a>"],
        [3, "GetGoState", "", "Returns the state of a <a class=\"mod\" href=\"GameObject/index.html\">GameObject</a> Below are client side [GOState]s off of 3.3.5a"],
        [3, "GetLootState", "", "Returns the [LootState] of a <a class=\"mod\" href=\"GameObject/index.html\">GameObject</a> Below are [LootState]s off of 3.3.5a"],
        [3, "HasQuest", "", "Returns 'true' if the <a class=\"mod\" href=\"GameObject/index.html\">GameObject</a> can give the specified <a class=\"mod\" href=\"Quest/index.html\">Quest</a>"],
        [3, "IsActive", "", "Returns 'true' if the <a class=\"mod\" href=\"GameObject/index.html\">GameObject</a> is active"],
        [3, "IsSpawned", "", "Returns 'true' if the <a class=\"mod\" href=\"GameObject/index.html\">GameObject</a> is spawned"],
        [3, "IsTransport", "", "Returns 'true' if the <a class=\"mod\" href=\"GameObject/index.html\">GameObject</a> is a transport"],
        [3, "RemoveFromWorld", "", "Removes <a class=\"mod\" href=\"GameObject/index.html\">GameObject</a> from the world"],
        [3, "Respawn", "", "Respawns a <a class=\"mod\" href=\"GameObject/index.html\">GameObject</a>"],
        [3, "SaveToDB", "", "Saves <a class=\"mod\" href=\"GameObject/index.html\">GameObject</a> to the database"],
        [3, "SetGoState", "", "Sets the state of a <a class=\"mod\" href=\"GameObject/index.html\">GameObject</a>"],
        [3, "SetLootState", "", "Sets the [LootState] of a <a class=\"mod\" href=\"GameObject/index.html\">GameObject</a> Below are [LootState]s off of 3.3.5a"],
        [3, "UseDoorOrButton", "", "Changes uses a door or a button type <a class=\"mod\" href=\"GameObject/index.html\">GameObject</a>"],
    ],
    "paths": []
};searchIndex["Global"] = {
    "items": [
        [0, "", "Global", ""],
        [3, "AddCorpse", "", "Adds a <a class=\"mod\" href=\"Corpse/index.html\">Corpse</a> to the world"],
        [3, "AddTaxiPath", "", "Adds a taxi path to a specified map, returns the used pathId Related function: <a class=\"fn\" href=\"Player/StartTaxi.html\">Player:StartTaxi</a>"],
        [3, "AddVendorItem", "", "Adds an <a class=\"mod\" href=\"Item/index.html\">Item</a> to a vendor"],
        [3, "AddWeather", "", "Adds <a class=\"mod\" href=\"Weather/index.html\">Weather</a> to a zone, also returns <a class=\"mod\" href=\"Weather/index.html\">Weather</a>"],
        [3, "AuthDBExecute", "", "Executes an sql to your auth database. The SQL is not ran instantly."],
        [3, "AuthDBQuery", "", "Executes an sql to your auth database instantly and returns <a class=\"mod\" href=\"ElunaQuery/index.html\">ElunaQuery</a>"],
        [3, "Ban", "", "Ban's a <a class=\"mod\" href=\"Player/index.html\">Player</a>'s account, character or IP"],
        [3, "CharDBExecute", "", "Executes an sql to your character database. The SQL is not ran instantly."],
        [3, "CharDBQuery", "", "Executes an sql to your character database instantly and returns <a class=\"mod\" href=\"ElunaQuery/index.html\">ElunaQuery</a>"],
        [3, "ConvertCorpseForPlayer", "", "Converts a <a class=\"mod\" href=\"Corpse/index.html\">Corpse</a> by guid, also allows for insignia to be looted"],
        [3, "CreateLongLong", "", "Returns an object represeting long long. The value by default is 0, but can be initialized to a value by passing a number or long long as a string."],
        [3, "CreateLuaEvent", "", "Registers a global timed event When the passed function is called, the parameters <code>(eventId, delay, repeats)</code> are passed to it. Repeats will decrease on each call if the event does not repeat indefinitely"],
        [3, "CreatePacket", "", "Creates a <a class=\"mod\" href=\"WorldPacket/index.html\">WorldPacket</a>"],
        [3, "CreateULongLong", "", "Returns an object represeting unsigned long long. The value by default is 0, but can be initialized to a value by passing a number or unsigned long long as a string."],
        [3, "FindWeather", "", "Finds <a class=\"mod\" href=\"Weather/index.html\">Weather</a> in a zone, also returns <a class=\"mod\" href=\"Weather/index.html\">Weather</a>"],
        [3, "GetAreaName", "", "Returns the area's or zone's name"],
        [3, "GetCoreExpansion", "", "Returns emulator expansion. Expansion is 0 for classic, 1 for TBC, 2 for WOTLK and 3 for cataclysm"],
        [3, "GetCoreName", "", "Returns emulator / core name. For example <code>MaNGOS</code>, <code>cMaNGOS</code> or <code>TrinityCore</code>"],
        [3, "GetCoreVersion", "", "Returns emulator version"],
        [3, "GetCurrTime", "", "Returns current time in ms"],
        [3, "GetGUIDEntry", "", "Returns the entry ID from a GUID. Entry ID is different for each <a class=\"mod\" href=\"Creature/index.html\">Creature</a> and <a class=\"mod\" href=\"GameObject/index.html\">GameObject</a>. <a class=\"mod\" href=\"Item/index.html\">Item</a> GUIDs dont include the entry GUID consist of entry ID, low GUID and type ID"],
        [3, "GetGUIDLow", "", "Returns the low GUID from a GUID. Low GUID is an ID to distinct the objects of the same type. <a class=\"mod\" href=\"Player/index.html\">Player</a> and <a class=\"mod\" href=\"Creature/index.html\">Creature</a> for example can have the same low GUID but not GUID. GUID consist of entry ID, low GUID and type ID"],
        [3, "GetGUIDType", "", "Returns the type ID from a GUID. Type ID is different for each type (<a class=\"mod\" href=\"Player/index.html\">Player</a>, <a class=\"mod\" href=\"Creature/index.html\">Creature</a>, <a class=\"mod\" href=\"GameObject/index.html\">GameObject</a>...) GUID consist of entry ID, low GUID and type ID"],
        [3, "GetGameTime", "", "Returns game time in seconds"],
        [3, "GetGuildByLeaderGUID", "", "Returns <a class=\"mod\" href=\"Guild/index.html\">Guild</a> by the leader's GUID"],
        [3, "GetGuildByName", "", "Returns <a class=\"mod\" href=\"Guild/index.html\">Guild</a> by name"],
        [3, "GetItemGUID", "", "Returns an <a class=\"mod\" href=\"Item/index.html\">Item</a>'s GUID <a class=\"mod\" href=\"Item/index.html\">Item</a> GUID consist of low GUID and type ID <a class=\"mod\" href=\"Player/index.html\">Player</a> and <a class=\"mod\" href=\"Item/index.html\">Item</a> for example can have the same low GUID but not GUID."],
        [3, "GetItemLink", "", "Returns an item chat link for given entry"],
        [3, "GetLuaEngine", "", "Returns lua engine name. Currently <code>ElunaEngine</code>"],
        [3, "GetMapById", "", "Returns <a class=\"mod\" href=\"Map/index.html\">Map</a> by ID"],
        [3, "GetObjectGUID", "", "Returns a <a class=\"mod\" href=\"GameObject/index.html\">GameObject</a>'s GUID <a class=\"mod\" href=\"GameObject/index.html\">GameObject</a> GUID consist of entry ID, low GUID and type ID <a class=\"mod\" href=\"Player/index.html\">Player</a> and <a class=\"mod\" href=\"GameObject/index.html\">GameObject</a> for example can have the same low GUID but not GUID."],
        [3, "GetPlayerByGUID", "", "Finds and Returns <a class=\"mod\" href=\"Player/index.html\">Player</a> by guid if found"],
        [3, "GetPlayerByName", "", "Finds and Returns <a class=\"mod\" href=\"Player/index.html\">Player</a> by name if found"],
        [3, "GetPlayerCount", "", "Returns the amount of <a class=\"mod\" href=\"Player/index.html\">Player</a>s in the world"],
        [3, "GetPlayerGUID", "", "Returns a <a class=\"mod\" href=\"Player/index.html\">Player</a>'s GUID <a class=\"mod\" href=\"Player/index.html\">Player</a> GUID consist of low GUID and type ID <a class=\"mod\" href=\"Player/index.html\">Player</a> and <a class=\"mod\" href=\"Creature/index.html\">Creature</a> for example can have the same low GUID but not GUID."],
        [3, "GetPlayersInMap", "", "Returns a table with all the current <a class=\"mod\" href=\"Player/index.html\">Player</a>s in a map"],
        [3, "GetPlayersInWorld", "", "Returns a table with all the current <a class=\"mod\" href=\"Player/index.html\">Player</a>s in the world"],
        [3, "GetQuest", "", "Returns <a class=\"mod\" href=\"Quest/index.html\">Quest</a> template"],
        [3, "GetTimeDiff", "", "Returns difference from a <a class=\"fn\" href=\"Global/GetCurrTime.html\">Global:GetCurrTime</a> time to now"],
        [3, "GetUnitGUID", "", "Returns a <a class=\"mod\" href=\"Creature/index.html\">Creature</a>'s GUID. <a class=\"mod\" href=\"Creature/index.html\">Creature</a> GUID consist of entry ID, low GUID and type ID <a class=\"mod\" href=\"Player/index.html\">Player</a> and <a class=\"mod\" href=\"Creature/index.html\">Creature</a> for example can have the same low GUID but not GUID."],
        [3, "IsBagPos", "", "Returns true if the bag and slot is a valid bag position, otherwise false"],
        [3, "IsBankPos", "", "Returns true if the bag and slot is a valid bank position, otherwise false"],
        [3, "IsEquipmentPos", "", "Returns true if the bag and slot is a valid equipment position, otherwise false"],
        [3, "IsInventoryPos", "", "Returns true if the bag and slot is a valid inventory position, otherwise false"],
        [3, "Kick", "", "Kicks a <a class=\"mod\" href=\"Player/index.html\">Player</a> from the server"],
        [3, "PerformIngameSpawn", "", "Performs an ingame spawn and returns <a class=\"mod\" href=\"Creature/index.html\">Creature</a> or <a class=\"mod\" href=\"GameObject/index.html\">GameObject</a> dependent on spawnType"],
        [3, "PrintDebug", "", "Prints given parameters to the debug log"],
        [3, "PrintError", "", "Prints given parameters to the error log"],
        [3, "PrintInfo", "", "Prints given parameters to the info log"],
        [3, "RegisterBGEvent", "", "Registers a [Battleground] event"],
        [3, "RegisterCreatureEvent", "", "Registers a <a class=\"mod\" href=\"Creature/index.html\">Creature</a> event"],
        [3, "RegisterCreatureGossipEvent", "", "Registers a <a class=\"mod\" href=\"Creature/index.html\">Creature</a> gossip event"],
        [3, "RegisterGameObjectEvent", "", "Registers a <a class=\"mod\" href=\"GameObject/index.html\">GameObject</a> event"],
        [3, "RegisterGameObjectGossipEvent", "", "Registers a <a class=\"mod\" href=\"GameObject/index.html\">GameObject</a> gossip event"],
        [3, "RegisterGroupEvent", "", "Registers a <a class=\"mod\" href=\"Group/index.html\">Group</a> event"],
        [3, "RegisterGuildEvent", "", "Registers a <a class=\"mod\" href=\"Guild/index.html\">Guild</a> event"],
        [3, "RegisterItemEvent", "", "Registers an <a class=\"mod\" href=\"Item/index.html\">Item</a> event"],
        [3, "RegisterItemGossipEvent", "", "Registers an <a class=\"mod\" href=\"Item/index.html\">Item</a> gossip event"],
        [3, "RegisterPacketEvent", "", "Registers a packet event"],
        [3, "RegisterPlayerEvent", "", "Registers a <a class=\"mod\" href=\"Player/index.html\">Player</a> event"],
        [3, "RegisterPlayerGossipEvent", "", "Registers a <a class=\"mod\" href=\"Player/index.html\">Player</a> gossip event"],
        [3, "RegisterServerEvent", "", "Registers a server event"],
        [3, "ReloadEluna", "", "Reloads the Lua Engine"],
        [3, "RemoveCorpse", "", "Removes a <a class=\"mod\" href=\"Corpse/index.html\">Corpse</a> from the world"],
        [3, "RemoveEventById", "", "Removes a global timed event specified by the event ID"],
        [3, "RemoveEvents", "", "Removes all global timed events"],
        [3, "RemoveOldCorpses", "", "Removes old <a class=\"mod\" href=\"Corpse/index.html\">Corpse</a>s from the world"],
        [3, "RemoveWeather", "", "Removes <a class=\"mod\" href=\"Weather/index.html\">Weather</a> from a zone"],
        [3, "SaveAllPlayers", "", "Saves all <a class=\"mod\" href=\"Player/index.html\">Player</a>s"],
        [3, "SendFineWeatherToPlayer", "", "Sends normal <a class=\"mod\" href=\"Weather/index.html\">Weather</a> to a <a class=\"mod\" href=\"Player/index.html\">Player</a>"],
        [3, "SendMail", "", "Sends mail to a <a class=\"mod\" href=\"Player/index.html\">Player</a> There can be several item entry-amount pairs at the end of the function. There can be maximum of 12 different items."],
        [3, "SendWorldMessage", "", "Sends a message to the world"],
        [3, "VendorRemoveAllItems", "", "Removes all <a class=\"mod\" href=\"Item/index.html\">Item</a>s from a vendor"],
        [3, "VendorRemoveItem", "", "Removes an <a class=\"mod\" href=\"Item/index.html\">Item</a> from a vendor"],
        [3, "WorldDBExecute", "", "Executes an sql to your character database. The SQL is not ran instantly."],
        [3, "WorldDBQuery", "", "Executes an sql to your world database instantly and returns <a class=\"mod\" href=\"ElunaQuery/index.html\">ElunaQuery</a>"],
        [3, "bit_and", "", "Returns the result of bitwise and: a &amp; b"],
        [3, "bit_lshift", "", "Returns the result of bitwise left shift: a &lt;&lt; b"],
        [3, "bit_not", "", "Returns the result of bitwise not: ~a"],
        [3, "bit_or", "", "Returns the result of bitwise or: a | b"],
        [3, "bit_rshift", "", "Returns the result of bitwise right shift: a &gt;&gt; b"],
        [3, "bit_xor", "", "Returns the result of bitwise xor: a ^ b"],
    ],
    "paths": []
};searchIndex["Group"] = {
    "items": [
        [0, "", "Group", ""],
        [3, "AddInvite", "", "Returns 'true' if the <a class=\"mod\" href=\"Group/index.html\">Group</a> invite was successful"],
        [3, "ConvertToRaid", "", "Converts this <a class=\"mod\" href=\"Group/index.html\">Group</a> to a raid <a class=\"mod\" href=\"Group/index.html\">Group</a>"],
        [3, "Disband", "", "Disbands this <a class=\"mod\" href=\"Group/index.html\">Group</a>"],
        [3, "GetGUID", "", "Returns the <a class=\"mod\" href=\"Group/index.html\">Group</a>'s GUID"],
        [3, "GetLeader", "", "Finds and returns a <a class=\"mod\" href=\"Group/index.html\">Group</a> leader by their GUID if logged in"],
        [3, "GetLeaderGUID", "", "Returns <a class=\"mod\" href=\"Group/index.html\">Group</a> leader GUID"],
        [3, "GetMemberGUID", "", "Returns a <a class=\"mod\" href=\"Group/index.html\">Group</a> member's GUID by their name"],
        [3, "GetMemberGroup", "", "Returns the <a class=\"mod\" href=\"Player/index.html\">Player</a>'s subgroup ID of this <a class=\"mod\" href=\"Group/index.html\">Group</a>"],
        [3, "GetMembers", "", "Returns a table with the <a class=\"mod\" href=\"Player/index.html\">Player</a>s in this <a class=\"mod\" href=\"Group/index.html\">Group</a>"],
        [3, "GetMembersCount", "", "Returns the member count of this <a class=\"mod\" href=\"Group/index.html\">Group</a>"],
        [3, "HasFreeSlotSubGroup", "", "Returns 'true' if the subgroup has free slots in this <a class=\"mod\" href=\"Group/index.html\">Group</a>"],
        [3, "IsAssistant", "", "Returns 'true' if the <a class=\"mod\" href=\"Player/index.html\">Player</a> is an assistant of this <a class=\"mod\" href=\"Group/index.html\">Group</a>"],
        [3, "IsBGGroup", "", "Returns 'true' if the <a class=\"mod\" href=\"Group/index.html\">Group</a> is a battleground <a class=\"mod\" href=\"Group/index.html\">Group</a>"],
        [3, "IsFull", "", "Returns 'true' if the <a class=\"mod\" href=\"Group/index.html\">Group</a> is full"],
        [3, "IsLeader", "", "Returns 'true' if the player is the <a class=\"mod\" href=\"Group/index.html\">Group</a> leader"],
        [3, "IsMember", "", "Returns 'true' if the <a class=\"mod\" href=\"Player/index.html\">Player</a> is a member of this <a class=\"mod\" href=\"Group/index.html\">Group</a>"],
        [3, "IsRaidGroup", "", "Returns 'true' if the <a class=\"mod\" href=\"Group/index.html\">Group</a> is a raid <a class=\"mod\" href=\"Group/index.html\">Group</a>"],
        [3, "RemoveMember", "", "Removes a member from this <a class=\"mod\" href=\"Group/index.html\">Group</a> and returns 'true' if successful"],
        [3, "SameSubGroup", "", "Returns 'true' if the <a class=\"mod\" href=\"Player/index.html\">Player</a>s are in the same subgroup in this <a class=\"mod\" href=\"Group/index.html\">Group</a>"],
        [3, "SendPacket", "", "Sends a specified <a class=\"mod\" href=\"WorldPacket/index.html\">WorldPacket</a> to this <a class=\"mod\" href=\"Group/index.html\">Group</a>"],
        [3, "SetLeader", "", "Sets the leader of this <a class=\"mod\" href=\"Group/index.html\">Group</a>"],
        [3, "SetMembersGroup", "", "Sets the member's subGroup"],
        [3, "SetTargetIcon", "", "Sets the target icon of an object for the <a class=\"mod\" href=\"Group/index.html\">Group</a>"],
    ],
    "paths": []
};searchIndex["Guild"] = {
    "items": [
        [0, "", "Guild", ""],
        [3, "AddMember", "", "Adds the specified <a class=\"mod\" href=\"Player/index.html\">Player</a> to the <a class=\"mod\" href=\"Guild/index.html\">Guild</a> at the specified rank."],
        [3, "DeleteMember", "", "Removes the specified <a class=\"mod\" href=\"Player/index.html\">Player</a> from the <a class=\"mod\" href=\"Guild/index.html\">Guild</a>."],
        [3, "DepositBankMoney", "", ""],
        [3, "Disband", "", "Disbands the <a class=\"mod\" href=\"Guild/index.html\">Guild</a>"],
        [3, "GetId", "", "Returns the <a class=\"mod\" href=\"Guild/index.html\">Guild</a>s entry ID"],
        [3, "GetInfo", "", "Returns the <a class=\"mod\" href=\"Guild/index.html\">Guild</a>s current info"],
        [3, "GetLeader", "", "Finds and returns the <a class=\"mod\" href=\"Guild/index.html\">Guild</a> leader by their GUID if logged in"],
        [3, "GetLeaderGUID", "", "Returns <a class=\"mod\" href=\"Guild/index.html\">Guild</a> leader GUID"],
        [3, "GetMOTD", "", "Returns the <a class=\"mod\" href=\"Guild/index.html\">Guild</a>s current Message Of The Day"],
        [3, "GetMemberCount", "", "Returns the member count of this <a class=\"mod\" href=\"Guild/index.html\">Guild</a>"],
        [3, "GetMembers", "", "Returns a table with the <a class=\"mod\" href=\"Player/index.html\">Player</a>s in this <a class=\"mod\" href=\"Guild/index.html\">Guild</a>"],
        [3, "GetName", "", "Returns the <a class=\"mod\" href=\"Guild/index.html\">Guild</a>s name"],
        [3, "SendPacket", "", "Sends a <a class=\"mod\" href=\"WorldPacket/index.html\">WorldPacket</a> to all the <a class=\"mod\" href=\"Player/index.html\">Player</a>s in the <a class=\"mod\" href=\"Guild/index.html\">Guild</a>"],
        [3, "SendPacketToRanked", "", "Sends a <a class=\"mod\" href=\"WorldPacket/index.html\">WorldPacket</a> to all the <a class=\"mod\" href=\"Player/index.html\">Player</a>s at the specified rank in the <a class=\"mod\" href=\"Guild/index.html\">Guild</a>"],
        [3, "SetBankTabText", "", "Sets the information of the bank tab specified"],
        [3, "SetLeader", "", "Sets the leader of this <a class=\"mod\" href=\"Guild/index.html\">Guild</a>"],
        [3, "SetMemberRank", "", "Promotes/demotes the <a class=\"mod\" href=\"Player/index.html\">Player</a> to the specified rank."],
        [3, "WithdrawBankMoney", "", ""],
    ],
    "paths": []
};searchIndex["Item"] = {
    "items": [
        [0, "", "Item", ""],
        [3, "CanBeTraded", "", "Returns 'true' if the <a class=\"mod\" href=\"Item/index.html\">Item</a> can be traded, 'false' otherwise"],
        [3, "ClearEnchantment", "", "Removes an enchant from the <a class=\"mod\" href=\"Item/index.html\">Item</a> by the specified slot"],
        [3, "GetAllowableClass", "", "Returns the <a class=\"mod\" href=\"Player/index.html\">Player</a> classes allowed to use this <a class=\"mod\" href=\"Item/index.html\">Item</a>"],
        [3, "GetAllowableRace", "", "Returns the <a class=\"mod\" href=\"Player/index.html\">Player</a> races allowed to use this <a class=\"mod\" href=\"Item/index.html\">Item</a>"],
        [3, "GetBagSize", "", "Returns the bag size of this <a class=\"mod\" href=\"Item/index.html\">Item</a>, 0 if <a class=\"mod\" href=\"Item/index.html\">Item</a> is not a bag"],
        [3, "GetBagSlot", "", "Returns the <a class=\"mod\" href=\"Item/index.html\">Item</a>s current bag slot"],
        [3, "GetBuyCount", "", "Returns the default purchase count of the <a class=\"mod\" href=\"Item/index.html\">Item</a>"],
        [3, "GetBuyPrice", "", "Returns the purchase price of the <a class=\"mod\" href=\"Item/index.html\">Item</a>"],
        [3, "GetClass", "", "Returns class of the <a class=\"mod\" href=\"Item/index.html\">Item</a>"],
        [3, "GetCount", "", "Returns the <a class=\"mod\" href=\"Item/index.html\">Item</a>s stack count"],
        [3, "GetDisplayId", "", "Returns the display ID of the <a class=\"mod\" href=\"Item/index.html\">Item</a>"],
        [3, "GetEnchantmentId", "", "Returns the <a class=\"mod\" href=\"Item/index.html\">Item</a>s enchantment ID by enchant slot specified"],
        [3, "GetInventoryType", "", "Returns the inventory type of the <a class=\"mod\" href=\"Item/index.html\">Item</a>"],
        [3, "GetItemLevel", "", "Returns the <a class=\"mod\" href=\"Item/index.html\">Item</a>s level"],
        [3, "GetItemLink", "", "Returns the chat link of the <a class=\"mod\" href=\"Item/index.html\">Item</a>"],
        [3, "GetItemSet", "", "Returns the item set ID of this <a class=\"mod\" href=\"Item/index.html\">Item</a>"],
        [3, "GetMaxStackCount", "", "Returns the <a class=\"mod\" href=\"Item/index.html\">Item</a>s max stack count"],
        [3, "GetName", "", "Returns the name of the <a class=\"mod\" href=\"Item/index.html\">Item</a>"],
        [3, "GetOwner", "", "Returns the <a class=\"mod\" href=\"Player/index.html\">Player</a> who currently owns the <a class=\"mod\" href=\"Item/index.html\">Item</a>"],
        [3, "GetOwnerGUID", "", ""],
        [3, "GetQuality", "", "Returns the quality of the <a class=\"mod\" href=\"Item/index.html\">Item</a>"],
        [3, "GetRandomProperty", "", "Returns the random property ID of this <a class=\"mod\" href=\"Item/index.html\">Item</a>"],
        [3, "GetRandomSuffix", "", ""],
        [3, "GetRequiredLevel", "", "Returns the minimum level required to use this <a class=\"mod\" href=\"Item/index.html\">Item</a>"],
        [3, "GetSellPrice", "", "Returns the sell price of the <a class=\"mod\" href=\"Item/index.html\">Item</a>"],
        [3, "GetSlot", "", "Returns the <a class=\"mod\" href=\"Item/index.html\">Item</a>s current slot"],
        [3, "GetSpellId", "", "Returns the spell ID tied to the <a class=\"mod\" href=\"Item/index.html\">Item</a> by spell index"],
        [3, "GetSpellTrigger", "", "Returns the spell trigger tied to the <a class=\"mod\" href=\"Item/index.html\">Item</a> by spell index"],
        [3, "GetStatsCount", "", ""],
        [3, "GetSubClass", "", "Returns subclass of the <a class=\"mod\" href=\"Item/index.html\">Item</a>"],
        [3, "HasQuest", "", "Returns 'true' if the <a class=\"mod\" href=\"Item/index.html\">Item</a> has the <a class=\"mod\" href=\"Quest/index.html\">Quest</a> specified tied to it, 'false' otherwise"],
        [3, "IsArmorVellum", "", "Returns 'true' if the <a class=\"mod\" href=\"Item/index.html\">Item</a> is an armor vellum, 'false' otherwise"],
        [3, "IsBag", "", "Returns 'true' if the <a class=\"mod\" href=\"Item/index.html\">Item</a> is a bag, 'false' otherwise"],
        [3, "IsBoundAccountWide", "", "Returns 'true' if the <a class=\"mod\" href=\"Item/index.html\">Item</a> is account bound, 'false' otherwise"],
        [3, "IsBoundByEnchant", "", "Returns 'true' if the <a class=\"mod\" href=\"Item/index.html\">Item</a> is bound to a <a class=\"mod\" href=\"Player/index.html\">Player</a> by an enchant, 'false' otehrwise"],
        [3, "IsBroken", "", "Returns 'true' if the <a class=\"mod\" href=\"Item/index.html\">Item</a> is broken, 'false' otherwise"],
        [3, "IsConjuredConsumable", "", "Returns 'true' if the <a class=\"mod\" href=\"Item/index.html\">Item</a> is a conjured consumable, 'false' otherwise"],
        [3, "IsCurrencyToken", "", "Returns 'true' if the <a class=\"mod\" href=\"Item/index.html\">Item</a> is a currency token, 'false' otherwise"],
        [3, "IsEquipped", "", "Returns 'true' if the <a class=\"mod\" href=\"Item/index.html\">Item</a> is currently equipped, 'false' otherwise"],
        [3, "IsInBag", "", "Returns 'true' if the <a class=\"mod\" href=\"Item/index.html\">Item</a> is currently in a bag, 'false' otherwise"],
        [3, "IsInTrade", "", "Returns 'true' if the <a class=\"mod\" href=\"Item/index.html\">Item</a> is currently in a trade window, 'false' otherwise"],
        [3, "IsLocked", "", "Returns 'true' if the <a class=\"mod\" href=\"Item/index.html\">Item</a> is locked, 'false' otherwise"],
        [3, "IsNotBoundToPlayer", "", "Returns 'true' if the <a class=\"mod\" href=\"Item/index.html\">Item</a> is not bound to the <a class=\"mod\" href=\"Player/index.html\">Player</a> specified, 'false' otherwise"],
        [3, "IsNotEmptyBag", "", "Returns 'true' if the <a class=\"mod\" href=\"Item/index.html\">Item</a> is a not an empty bag, 'false' otherwise"],
        [3, "IsPotion", "", "Returns 'true' if the <a class=\"mod\" href=\"Item/index.html\">Item</a> is a potion, 'false' otherwise"],
        [3, "IsSoulBound", "", "Returns 'true' if the <a class=\"mod\" href=\"Item/index.html\">Item</a> is soulbound, 'false' otherwise"],
        [3, "IsWeaponVellum", "", "Returns 'true' if the <a class=\"mod\" href=\"Item/index.html\">Item</a> is a weapon vellum, 'false' otherwise"],
        [3, "SaveToDB", "", "Saves the <a class=\"mod\" href=\"Item/index.html\">Item</a> to the database"],
        [3, "SetBinding", "", "Sets the binding of the <a class=\"mod\" href=\"Item/index.html\">Item</a> to 'true' or 'false'"],
        [3, "SetCount", "", "Sets the stack count of the <a class=\"mod\" href=\"Item/index.html\">Item</a>"],
        [3, "SetEnchantment", "", "Sets the specified enchantment of the <a class=\"mod\" href=\"Item/index.html\">Item</a> to the specified slot"],
        [3, "SetOwner", "", "Sets the <a class=\"mod\" href=\"Player/index.html\">Player</a> specified as the owner of the <a class=\"mod\" href=\"Item/index.html\">Item</a>"],
    ],
    "paths": []
};searchIndex["Map"] = {
    "items": [
        [0, "", "Map", ""],
        [3, "GetAreaId", "", "Returns the area ID of the <a class=\"mod\" href=\"Map/index.html\">Map</a> at the specified X, Y and Z coordinates"],
        [3, "GetDifficulty", "", "Returns the difficulty of the <a class=\"mod\" href=\"Map/index.html\">Map</a>"],
        [3, "GetHeight", "", "Returns the height of the <a class=\"mod\" href=\"Map/index.html\">Map</a> at the given X and Y coordinates In case of no height found nil is returned"],
        [3, "GetInstanceId", "", "Returns the instance ID of the <a class=\"mod\" href=\"Map/index.html\">Map</a>"],
        [3, "GetMapId", "", "Returns the ID of the <a class=\"mod\" href=\"Map/index.html\">Map</a>"],
        [3, "GetName", "", "Returns the name of the <a class=\"mod\" href=\"Map/index.html\">Map</a>"],
        [3, "GetPlayerCount", "", "Returns the player count currently on the <a class=\"mod\" href=\"Map/index.html\">Map</a> Does not include gamemasters"],
        [3, "GetWorldObject", "", "Returns a <a class=\"mod\" href=\"WorldObject/index.html\">WorldObject</a> by it's guid from the map if it is spawned"],
        [3, "IsArena", "", "Returns 'true' if the <a class=\"mod\" href=\"Map/index.html\">Map</a> is an arena, false otherwise"],
        [3, "IsBattleground", "", "Returns 'true' if the <a class=\"mod\" href=\"Map/index.html\">Map</a> is a battleground, false otherwise"],
        [3, "IsDungeon", "", "Returns 'true' if the <a class=\"mod\" href=\"Map/index.html\">Map</a> is a dungeon, false otherwise"],
        [3, "IsEmpty", "", "Returns 'true' if the <a class=\"mod\" href=\"Map/index.html\">Map</a> is empty, false otherwise"],
        [3, "IsHeroic", "", "Returns 'true' if the <a class=\"mod\" href=\"Map/index.html\">Map</a> is a heroic, false otherwise"],
        [3, "IsRaid", "", "Returns 'true' if the <a class=\"mod\" href=\"Map/index.html\">Map</a> is a raid, false otherwise"],
    ],
    "paths": []
};searchIndex["Object"] = {
    "items": [
        [0, "", "Object", ""],
        [3, "GetByteValue", "", ""],
        [3, "GetEntry", "", ""],
        [3, "GetFloatValue", "", ""],
        [3, "GetGUID", "", ""],
        [3, "GetGUIDLow", "", ""],
        [3, "GetInt32Value", "", ""],
        [3, "GetScale", "", ""],
        [3, "GetTypeId", "", ""],
        [3, "GetUInt16Value", "", ""],
        [3, "GetUInt32Value", "", ""],
        [3, "GetUInt64Value", "", ""],
        [3, "HasFlag", "", ""],
        [3, "IsInWorld", "", ""],
        [3, "RemoveFlag", "", ""],
        [3, "SetByteValue", "", ""],
        [3, "SetFlag", "", ""],
        [3, "SetFloatValue", "", ""],
        [3, "SetInt16Value", "", ""],
        [3, "SetInt32Value", "", ""],
        [3, "SetScale", "", ""],
        [3, "SetUInt16Value", "", ""],
        [3, "SetUInt32Value", "", ""],
        [3, "SetUInt64Value", "", ""],
        [3, "ToCorpse", "", ""],
        [3, "ToCreature", "", ""],
        [3, "ToGameObject", "", ""],
        [3, "ToPlayer", "", ""],
        [3, "ToUnit", "", ""],
        [3, "UpdateUInt32Value", "", ""],
    ],
    "paths": []
};searchIndex["Player"] = {
    "items": [
        [0, "", "Player", ""],
        [3, "AddComboPoints", "", ""],
        [3, "AddItem", "", ""],
        [3, "AddLifetimeKills", "", ""],
        [3, "AdvanceAllSkills", "", ""],
        [3, "AdvanceSkill", "", ""],
        [3, "AdvanceSkillsToMax", "", ""],
        [3, "AreaExploredOrEventHappens", "", ""],
        [3, "CanBlock", "", ""],
        [3, "CanEquipItem", "", ""],
        [3, "CanFly", "", ""],
        [3, "CanParry", "", ""],
        [3, "CanShareQuest", "", ""],
        [3, "CanSpeak", "", ""],
        [3, "CanTitanGrip", "", ""],
        [3, "CanUninviteFromGroup", "", ""],
        [3, "CanUseItem", "", ""],
        [3, "ClearComboPoints", "", ""],
        [3, "ClearHonorInfo", "", ""],
        [3, "CompleteQuest", "", ""],
        [3, "CreateCorpse", "", ""],
        [3, "DurabilityLoss", "", ""],
        [3, "DurabilityLossAll", "", ""],
        [3, "DurabilityPointLossForEquipSlot", "", ""],
        [3, "DurabilityPointsLoss", "", ""],
        [3, "DurabilityPointsLossAll", "", ""],
        [3, "DurabilityRepair", "", ""],
        [3, "DurabilityRepairAll", "", ""],
        [3, "EquipItem", "", ""],
        [3, "FailQuest", "", ""],
        [3, "GetAccountId", "", ""],
        [3, "GetAccountName", "", ""],
        [3, "GetActiveSpec", "", ""],
        [3, "GetArenaPoints", "", ""],
        [3, "GetBaseSkillValue", "", ""],
        [3, "GetBattlegroundId", "", ""],
        [3, "GetBattlegroundTypeId", "", ""],
        [3, "GetChampioningFaction", "", ""],
        [3, "GetChatTag", "", ""],
        [3, "GetCoinage", "", ""],
        [3, "GetComboPoints", "", ""],
        [3, "GetComboTarget", "", ""],
        [3, "GetCorpse", "", ""],
        [3, "GetDbLocaleIndex", "", ""],
        [3, "GetDbcLocale", "", ""],
        [3, "GetDifficulty", "", ""],
        [3, "GetDrunkValue", "", ""],
        [3, "GetEquippedItemBySlot", "", ""],
        [3, "GetFreeTalentPoints", "", ""],
        [3, "GetGMRank", "", ""],
        [3, "GetGossipTextId", "", ""],
        [3, "GetGroup", "", ""],
        [3, "GetGroupInvite", "", ""],
        [3, "GetGuild", "", ""],
        [3, "GetGuildId", "", ""],
        [3, "GetGuildName", "", ""],
        [3, "GetGuildRank", "", ""],
        [3, "GetHealthBonusFromStamina", "", ""],
        [3, "GetHonorLastWeekStandingPos", "", ""],
        [3, "GetHonorPoints", "", ""],
        [3, "GetHonorStoredKills", "", ""],
        [3, "GetInGameTime", "", ""],
        [3, "GetItemByEntry", "", ""],
        [3, "GetItemByPos", "", "Returns an item in given bag on given slot."],
        [3, "GetItemCount", "", ""],
        [3, "GetLatency", "", ""],
        [3, "GetLevelPlayedTime", "", ""],
        [3, "GetLifetimeKills", "", ""],
        [3, "GetManaBonusFromIntellect", "", ""],
        [3, "GetMaxSkillValue", "", ""],
        [3, "GetNextRandomRaidMember", "", ""],
        [3, "GetOriginalGroup", "", ""],
        [3, "GetOriginalSubGroup", "", ""],
        [3, "GetPhaseMaskForSpawn", "", ""],
        [3, "GetPlayerIP", "", ""],
        [3, "GetPureMaxSkillValue", "", ""],
        [3, "GetPureSkillValue", "", ""],
        [3, "GetQuestLevel", "", ""],
        [3, "GetQuestRewardStatus", "", ""],
        [3, "GetQuestStatus", "", ""],
        [3, "GetRankPoints", "", ""],
        [3, "GetReputation", "", ""],
        [3, "GetReputationRank", "", ""],
        [3, "GetReqKillOrCastCurrentCount", "", ""],
        [3, "GetRestBonus", "", ""],
        [3, "GetRestTime", "", ""],
        [3, "GetRestType", "", ""],
        [3, "GetSelection", "", ""],
        [3, "GetShieldBlockValue", "", ""],
        [3, "GetSkillPermBonusValue", "", ""],
        [3, "GetSkillTempBonusValue", "", ""],
        [3, "GetSkillValue", "", ""],
        [3, "GetSpecsCount", "", ""],
        [3, "GetSpellCooldownDelay", "", ""],
        [3, "GetSpellCooldowns", "", ""],
        [3, "GetSubGroup", "", ""],
        [3, "GetTeam", "", ""],
        [3, "GetTotalPlayedTime", "", ""],
        [3, "GetXPRestBonus", "", ""],
        [3, "GiveLevel", "", ""],
        [3, "GiveXP", "", ""],
        [3, "GossipAddQuests", "", ""],
        [3, "GossipClearMenu", "", ""],
        [3, "GossipComplete", "", ""],
        [3, "GossipMenuAddItem", "", ""],
        [3, "GossipSendMenu", "", ""],
        [3, "GossipSendPOI", "", ""],
        [3, "GroupEventHappens", "", ""],
        [3, "HasAchieved", "", ""],
        [3, "HasAtLoginFlag", "", ""],
        [3, "HasItem", "", ""],
        [3, "HasQuest", "", ""],
        [3, "HasQuestForGO", "", ""],
        [3, "HasQuestForItem", "", ""],
        [3, "HasSkill", "", ""],
        [3, "HasSpell", "", ""],
        [3, "HasSpellCooldown", "", ""],
        [3, "HasTalent", "", ""],
        [3, "HasTitle", "", ""],
        [3, "InArena", "", ""],
        [3, "InBattleground", "", ""],
        [3, "InBattlegroundQueue", "", ""],
        [3, "IncompleteQuest", "", ""],
        [3, "IsAFK", "", ""],
        [3, "IsAcceptingWhispers", "", ""],
        [3, "IsAlliance", "", ""],
        [3, "IsDND", "", ""],
        [3, "IsFalling", "", ""],
        [3, "IsFlying", "", ""],
        [3, "IsGM", "", ""],
        [3, "IsGMChat", "", ""],
        [3, "IsGMVisible", "", ""],
        [3, "IsGroupVisibleFor", "", ""],
        [3, "IsHonorOrXPTarget", "", ""],
        [3, "IsHorde", "", ""],
        [3, "IsInArenaTeam", "", ""],
        [3, "IsInGroup", "", ""],
        [3, "IsInGuild", "", ""],
        [3, "IsInSameGroupWith", "", ""],
        [3, "IsInSameRaidWith", "", ""],
        [3, "IsInWater", "", ""],
        [3, "IsMoving", "", ""],
        [3, "IsRested", "", ""],
        [3, "IsTaxiCheater", "", ""],
        [3, "IsVisibleForPlayer", "", ""],
        [3, "KickPlayer", "", ""],
        [3, "KillPlayer", "", ""],
        [3, "KilledMonsterCredit", "", ""],
        [3, "LearnSpell", "", ""],
        [3, "LeaveBattleground", "", ""],
        [3, "LogoutPlayer", "", ""],
        [3, "ModifyArenaPoints", "", ""],
        [3, "ModifyHonorPoints", "", ""],
        [3, "ModifyMoney", "", ""],
        [3, "Mute", "", ""],
        [3, "PlaySoundToPlayer", "", ""],
        [3, "RemoveFromBattlegroundRaid", "", ""],
        [3, "RemoveFromGroup", "", ""],
        [3, "RemoveItem", "", ""],
        [3, "RemoveLifetimeKills", "", ""],
        [3, "RemoveSpell", "", ""],
        [3, "RemovedInsignia", "", ""],
        [3, "ResetAchievements", "", ""],
        [3, "ResetAllCooldowns", "", ""],
        [3, "ResetHonor", "", ""],
        [3, "ResetPetTalents", "", ""],
        [3, "ResetSpellCooldown", "", ""],
        [3, "ResetTalents", "", ""],
        [3, "ResetTalentsCost", "", ""],
        [3, "ResetTypeCooldowns", "", ""],
        [3, "ResurrectPlayer", "", ""],
        [3, "RewardQuest", "", ""],
        [3, "SaveToDB", "", ""],
        [3, "Say", "", ""],
        [3, "SendAddonMessage", "", ""],
        [3, "SendAreaTriggerMessage", "", ""],
        [3, "SendAuctionMenu", "", ""],
        [3, "SendBroadcastMessage", "", ""],
        [3, "SendClearCooldowns", "", ""],
        [3, "SendGuildInvite", "", ""],
        [3, "SendListInventory", "", ""],
        [3, "SendNotification", "", ""],
        [3, "SendPacket", "", ""],
        [3, "SendQuestTemplate", "", ""],
        [3, "SendShowBank", "", ""],
        [3, "SendShowMailBox", "", ""],
        [3, "SendSpiritResurrect", "", ""],
        [3, "SendTabardVendorActivate", "", ""],
        [3, "SendTaxiMenu", "", ""],
        [3, "SendTrainerList", "", ""],
        [3, "SendVendorWindow", "", ""],
        [3, "SetAcceptWhispers", "", ""],
        [3, "SetArenaPoints", "", ""],
        [3, "SetAtLoginFlag", "", ""],
        [3, "SetBindPoint", "", ""],
        [3, "SetCoinage", "", ""],
        [3, "SetDrunkValue", "", ""],
        [3, "SetFFA", "", ""],
        [3, "SetFactionForRace", "", ""],
        [3, "SetFreeTalentPoints", "", ""],
        [3, "SetGMChat", "", ""],
        [3, "SetGMVisible", "", ""],
        [3, "SetGameMaster", "", ""],
        [3, "SetGender", "", ""],
        [3, "SetGuildRank", "", ""],
        [3, "SetHonorLastWeekStandingPos", "", ""],
        [3, "SetHonorPoints", "", ""],
        [3, "SetHonorStoredKills", "", ""],
        [3, "SetKnownTitle", "", ""],
        [3, "SetLifetimeKills", "", ""],
        [3, "SetPlayerLock", "", ""],
        [3, "SetPvPDeath", "", ""],
        [3, "SetQuestStatus", "", ""],
        [3, "SetRankPoints", "", ""],
        [3, "SetReputation", "", ""],
        [3, "SetRestBonus", "", ""],
        [3, "SetRestTime", "", ""],
        [3, "SetRestType", "", ""],
        [3, "SetSheath", "", ""],
        [3, "SetSkill", "", ""],
        [3, "SetTaxiCheat", "", ""],
        [3, "SpawnBones", "", ""],
        [3, "StartTaxi", "", ""],
        [3, "SummonPlayer", "", ""],
        [3, "TalkedToCreature", "", ""],
        [3, "Teleport", "", ""],
        [3, "TextEmote", "", ""],
        [3, "ToggleAFK", "", ""],
        [3, "ToggleDND", "", ""],
        [3, "UnbindInstance", "", ""],
        [3, "UnsetKnownTitle", "", ""],
        [3, "UpdateHonor", "", ""],
        [3, "Whisper", "", ""],
        [3, "Yell", "", ""],
    ],
    "paths": []
};searchIndex["Quest"] = {
    "items": [
        [0, "", "Quest", ""],
        [3, "GetFlags", "", "Returns the <a class=\"mod\" href=\"Quest/index.html\">Quest</a>'s flags."],
        [3, "GetId", "", "Returns entry ID of the <a class=\"mod\" href=\"Quest/index.html\">Quest</a>."],
        [3, "GetLevel", "", "Returns the <a class=\"mod\" href=\"Quest/index.html\">Quest</a>'s level."],
        [3, "GetMinLevel", "", "Returns the minimum level required to pick up the <a class=\"mod\" href=\"Quest/index.html\">Quest</a>."],
        [3, "GetNextQuestId", "", "Returns the next <a class=\"mod\" href=\"Quest/index.html\">Quest</a> entry ID."],
        [3, "GetNextQuestInChain", "", "Returns the next <a class=\"mod\" href=\"Quest/index.html\">Quest</a> entry ID in the specific <a class=\"mod\" href=\"Quest/index.html\">Quest</a> chain."],
        [3, "GetPrevQuestId", "", "Returns the previous <a class=\"mod\" href=\"Quest/index.html\">Quest</a> entry ID."],
        [3, "GetType", "", "Returns the <a class=\"mod\" href=\"Quest/index.html\">Quest</a>'s type."],
        [3, "HasFlag", "", "Returns 'true' if the <a class=\"mod\" href=\"Quest/index.html\">Quest</a> has the specified flag, false otherwise. Below flags are based off of 3.3.5a. Subject to change."],
        [3, "IsDaily", "", "Returns 'true' if the <a class=\"mod\" href=\"Quest/index.html\">Quest</a> is a daily quest, false otherwise."],
        [3, "IsRepeatable", "", "Returns 'true' if the <a class=\"mod\" href=\"Quest/index.html\">Quest</a> is repeatable, false otherwise."],
    ],
    "paths": []
};searchIndex["Spell"] = {
    "items": [
        [0, "", "Spell", ""],
        [3, "Cancel", "", "Cancels the <a class=\"mod\" href=\"Spell/index.html\">Spell</a>."],
        [3, "Cast", "", "Casts the <a class=\"mod\" href=\"Spell/index.html\">Spell</a>."],
        [3, "Finish", "", "Finishes the <a class=\"mod\" href=\"Spell/index.html\">Spell</a>."],
        [3, "GetCastTime", "", "Returns the cast time of the <a class=\"mod\" href=\"Spell/index.html\">Spell</a>."],
        [3, "GetCaster", "", "Returns the <a class=\"mod\" href=\"Unit/index.html\">Unit</a> that casted the <a class=\"mod\" href=\"Spell/index.html\">Spell</a>."],
        [3, "GetDuration", "", "Returns the spell duration of the <a class=\"mod\" href=\"Spell/index.html\">Spell</a>."],
        [3, "GetEntry", "", "Returns the entry ID of the <a class=\"mod\" href=\"Spell/index.html\">Spell</a>."],
        [3, "GetPowerCost", "", "Returns the power cost of the <a class=\"mod\" href=\"Spell/index.html\">Spell</a>."],
        [3, "GetTarget", "", "Returns the target <a class=\"mod\" href=\"Object/index.html\">Object</a> of the <a class=\"mod\" href=\"Spell/index.html\">Spell</a>. Target can be any of the following <a class=\"mod\" href=\"Object/index.html\">Object</a> types: <a class=\"mod\" href=\"Player/index.html\">Player</a>, <a class=\"mod\" href=\"Creature/index.html\">Creature</a>, <a class=\"mod\" href=\"GameObject/index.html\">GameObject</a>, <a class=\"mod\" href=\"Item/index.html\">Item</a>, <a class=\"mod\" href=\"Corpse/index.html\">Corpse</a>"],
        [3, "GetTargetDest", "", "Returns the target destination coordinates of the <a class=\"mod\" href=\"Spell/index.html\">Spell</a>."],
        [3, "IsAutoRepeat", "", "Returns 'true' if the <a class=\"mod\" href=\"Spell/index.html\">Spell</a> is automatically repeating, false otherwise."],
        [3, "SetAutoRepeat", "", "Sets the <a class=\"mod\" href=\"Spell/index.html\">Spell</a> to automatically repeat."],
    ],
    "paths": []
};searchIndex["Unit"] = {
    "items": [
        [0, "", "Unit", ""],
        [3, "AddAura", "", ""],
        [3, "AddThreat", "", "Adds threat to the <a class=\"mod\" href=\"Unit/index.html\">Unit</a> from the victim."],
        [3, "AddUnitState", "", ""],
        [3, "Attack", "", ""],
        [3, "AttackStop", "", ""],
        [3, "CastCustomSpell", "", "Casts the <a class=\"mod\" href=\"Spell/index.html\">Spell</a> at target <a class=\"mod\" href=\"Unit/index.html\">Unit</a> with custom basepoints or casters. See also <a class=\"fn\" href=\"Unit/CastSpell.html\">Unit:CastSpell</a>."],
        [3, "CastSpell", "", ""],
        [3, "CastSpellAoF", "", ""],
        [3, "ClearInCombat", "", ""],
        [3, "ClearThreatList", "", ""],
        [3, "ClearUnitState", "", ""],
        [3, "CountPctFromCurHealth", "", ""],
        [3, "CountPctFromMaxHealth", "", ""],
        [3, "DeMorph", "", ""],
        [3, "DealDamage", "", "Makes the <a class=\"mod\" href=\"Unit/index.html\">Unit</a> damage the target <a class=\"mod\" href=\"Unit/index.html\">Unit</a>"],
        [3, "DealHeal", "", "Makes the <a class=\"mod\" href=\"Unit/index.html\">Unit</a> heal the target <a class=\"mod\" href=\"Unit/index.html\">Unit</a> with given spell"],
        [3, "Dismount", "", ""],
        [3, "Emote", "", ""],
        [3, "GetAura", "", ""],
        [3, "GetBaseSpellPower", "", ""],
        [3, "GetCharmGUID", "", ""],
        [3, "GetCharmerGUID", "", ""],
        [3, "GetClass", "", ""],
        [3, "GetClassAsString", "", "Returns the <a class=\"mod\" href=\"Unit/index.html\">Unit</a>'s class' name in given or default locale or nil."],
        [3, "GetCombatTime", "", ""],
        [3, "GetControllerGUID", "", ""],
        [3, "GetControllerGUIDS", "", ""],
        [3, "GetCreatorGUID", "", ""],
        [3, "GetCreatureType", "", ""],
        [3, "GetCritterGUID", "", ""],
        [3, "GetCurrentSpell", "", "Returns the currently casted <a class=\"mod\" href=\"Spell/index.html\">Spell</a> of given type or nil"],
        [3, "GetDisplayId", "", ""],
        [3, "GetFaction", "", ""],
        [3, "GetFriendlyUnitsInRange", "", ""],
        [3, "GetGender", "", ""],
        [3, "GetHealth", "", ""],
        [3, "GetHealthPct", "", ""],
        [3, "GetLevel", "", ""],
        [3, "GetMaxHealth", "", ""],
        [3, "GetMaxPower", "", ""],
        [3, "GetMinionGUID", "", ""],
        [3, "GetMountId", "", ""],
        [3, "GetMovementType", "", ""],
        [3, "GetNativeDisplayId", "", ""],
        [3, "GetOwner", "", ""],
        [3, "GetOwnerGUID", "", ""],
        [3, "GetPetGUID", "", ""],
        [3, "GetPower", "", ""],
        [3, "GetPowerPct", "", ""],
        [3, "GetPowerType", "", ""],
        [3, "GetRace", "", ""],
        [3, "GetRaceAsString", "", "Returns the <a class=\"mod\" href=\"Unit/index.html\">Unit</a>'s race's name in given or default locale or nil."],
        [3, "GetSpeed", "", "Returns the <a class=\"mod\" href=\"Unit/index.html\">Unit</a>'s speed of given [UnitMoveType]."],
        [3, "GetStandState", "", ""],
        [3, "GetStat", "", ""],
        [3, "GetUnfriendlyUnitsInRange", "", ""],
        [3, "GetVehicle", "", ""],
        [3, "GetVehicleKit", "", ""],
        [3, "GetVictim", "", ""],
        [3, "HasAura", "", ""],
        [3, "HasUnitState", "", ""],
        [3, "HealthAbovePct", "", ""],
        [3, "HealthBelowPct", "", ""],
        [3, "InterruptSpell", "", ""],
        [3, "IsAlive", "", ""],
        [3, "IsArmorer", "", ""],
        [3, "IsAttackingPlayer", "", ""],
        [3, "IsAuctioneer", "", ""],
        [3, "IsBanker", "", ""],
        [3, "IsBattleMaster", "", ""],
        [3, "IsCharmed", "", ""],
        [3, "IsDead", "", ""],
        [3, "IsDying", "", ""],
        [3, "IsFullHealth", "", ""],
        [3, "IsGossip", "", ""],
        [3, "IsGuildMaster", "", ""],
        [3, "IsInAccessiblePlaceFor", "", ""],
        [3, "IsInCombat", "", ""],
        [3, "IsInWater", "", ""],
        [3, "IsInnkeeper", "", ""],
        [3, "IsMounted", "", ""],
        [3, "IsOnVehicle", "", ""],
        [3, "IsPvPFlagged", "", ""],
        [3, "IsQuestGiver", "", ""],
        [3, "IsRooted", "", ""],
        [3, "IsServiceProvider", "", ""],
        [3, "IsSpiritGuide", "", ""],
        [3, "IsSpiritHealer", "", ""],
        [3, "IsSpiritService", "", ""],
        [3, "IsStandState", "", ""],
        [3, "IsStopped", "", ""],
        [3, "IsTabardDesigner", "", ""],
        [3, "IsTaxi", "", ""],
        [3, "IsTrainer", "", ""],
        [3, "IsUnderWater", "", ""],
        [3, "IsVendor", "", ""],
        [3, "IsWithinDistInMap", "", ""],
        [3, "Kill", "", "Makes the <a class=\"mod\" href=\"Unit/index.html\">Unit</a> kill the target <a class=\"mod\" href=\"Unit/index.html\">Unit</a>"],
        [3, "Mount", "", ""],
        [3, "MoveChase", "", ""],
        [3, "MoveClear", "", ""],
        [3, "MoveConfused", "", ""],
        [3, "MoveExpire", "", ""],
        [3, "MoveFleeing", "", ""],
        [3, "MoveFollow", "", ""],
        [3, "MoveHome", "", ""],
        [3, "MoveIdle", "", ""],
        [3, "MoveJump", "", ""],
        [3, "MoveRandom", "", ""],
        [3, "MoveStop", "", ""],
        [3, "MoveTo", "", ""],
        [3, "NearTeleport", "", ""],
        [3, "PlayDirectSound", "", ""],
        [3, "PlayDistanceSound", "", ""],
        [3, "RemoveAllAuras", "", ""],
        [3, "RemoveAura", "", ""],
        [3, "SendChatMessageToPlayer", "", ""],
        [3, "SendUnitEmote", "", ""],
        [3, "SendUnitSay", "", ""],
        [3, "SendUnitWhisper", "", ""],
        [3, "SendUnitYell", "", ""],
        [3, "SetCharmerGUID", "", ""],
        [3, "SetCreatorGUID", "", ""],
        [3, "SetCritterGUID", "", ""],
        [3, "SetDisplayId", "", ""],
        [3, "SetFFA", "", ""],
        [3, "SetFacing", "", ""],
        [3, "SetFacingToObject", "", ""],
        [3, "SetFaction", "", ""],
        [3, "SetHealth", "", ""],
        [3, "SetLevel", "", ""],
        [3, "SetMaxHealth", "", ""],
        [3, "SetMaxPower", "", ""],
        [3, "SetMinionGUID", "", ""],
        [3, "SetName", "", ""],
        [3, "SetNativeDisplayId", "", ""],
        [3, "SetOwnerGUID", "", ""],
        [3, "SetPetGUID", "", ""],
        [3, "SetPhaseMask", "", ""],
        [3, "SetPower", "", ""],
        [3, "SetPowerType", "", ""],
        [3, "SetPvP", "", ""],
        [3, "SetSanctuary", "", ""],
        [3, "SetSheath", "", ""],
        [3, "SetSpeed", "", "Sets the <a class=\"mod\" href=\"Unit/index.html\">Unit</a>'s speed of given [UnitMoveType] to given rate. If forced, packets sent to clients forcing the visual change."],
        [3, "SetStandState", "", ""],
        [3, "SetWaterWalk", "", ""],
        [3, "StopSpellCast", "", ""],
    ],
    "paths": []
};searchIndex["Vehicle"] = {
    "items": [
        [0, "", "Vehicle", ""],
        [3, "AddPassenger", "", ""],
        [3, "GetEntry", "", ""],
        [3, "GetOwner", "", ""],
        [3, "GetPassenger", "", ""],
        [3, "IsOnBoard", "", ""],
        [3, "RemovePassenger", "", ""],
    ],
    "paths": []
};searchIndex["Weather"] = {
    "items": [
        [0, "", "Weather", ""],
        [3, "GetZoneId", "", "Returns the zone id of the <a class=\"mod\" href=\"Weather/index.html\">Weather</a>"],
        [3, "Regenerate", "", "Regenerates the <a class=\"mod\" href=\"Weather/index.html\">Weather</a>, causing it to change based on the below statistics."],
        [3, "SendWeatherUpdateToPlayer", "", "Sends a <a class=\"mod\" href=\"Weather/index.html\">Weather</a> update to the <a class=\"mod\" href=\"Player/index.html\">Player</a> supplied."],
        [3, "SetWeather", "", "Sets the <a class=\"mod\" href=\"Weather/index.html\">Weather</a> type based on [WeatherType] and grade supplied."],
        [3, "UpdateWeather", "", "Sends a <a class=\"mod\" href=\"Weather/index.html\">Weather</a> update to the all <a class=\"mod\" href=\"Player/index.html\">Player</a> in the zone."],
    ],
    "paths": []
};searchIndex["WorldObject"] = {
    "items": [
        [0, "", "WorldObject", ""],
        [3, "GetAngle", "", "Returns the angle between this <a class=\"mod\" href=\"WorldObject/index.html\">WorldObject</a> and another <a class=\"mod\" href=\"WorldObject/index.html\">WorldObject</a> or a point. The angle is the angle between two points and orientation will be ignored."],
        [3, "GetAreaId", "", "Returns the current area ID of the <a class=\"mod\" href=\"WorldObject/index.html\">WorldObject</a>"],
        [3, "GetCreaturesInRange", "", "Returns a table of <a class=\"mod\" href=\"Creature/index.html\">Creature</a> objects in sight of the <a class=\"mod\" href=\"WorldObject/index.html\">WorldObject</a> or within the given range and/or with a specific entry ID"],
        [3, "GetDistance", "", "Returns the distance from this <a class=\"mod\" href=\"WorldObject/index.html\">WorldObject</a> to another <a class=\"mod\" href=\"WorldObject/index.html\">WorldObject</a>, or from this <a class=\"mod\" href=\"WorldObject/index.html\">WorldObject</a> to a point."],
        [3, "GetGameObjectsInRange", "", "Returns a table of <a class=\"mod\" href=\"GameObject/index.html\">GameObject</a> objects in sight of the <a class=\"mod\" href=\"WorldObject/index.html\">WorldObject</a> or within the given range and/or with a specific entry ID"],
        [3, "GetInstanceId", "", "Returns the current instance ID of the <a class=\"mod\" href=\"WorldObject/index.html\">WorldObject</a>"],
        [3, "GetLocation", "", "Returns the coordinates and orientation of the <a class=\"mod\" href=\"WorldObject/index.html\">WorldObject</a>"],
        [3, "GetMap", "", "Returns the current <a class=\"mod\" href=\"Map/index.html\">Map</a> object of the <a class=\"mod\" href=\"WorldObject/index.html\">WorldObject</a>"],
        [3, "GetMapId", "", "Returns the current map ID of the <a class=\"mod\" href=\"WorldObject/index.html\">WorldObject</a>"],
        [3, "GetName", "", "Returns the name of the <a class=\"mod\" href=\"WorldObject/index.html\">WorldObject</a>"],
        [3, "GetNearObject", "", "Returns nearest <a class=\"mod\" href=\"WorldObject/index.html\">WorldObject</a> in sight of the <a class=\"mod\" href=\"WorldObject/index.html\">WorldObject</a>. The distance, type, entry and hostility requirements the <a class=\"mod\" href=\"WorldObject/index.html\">WorldObject</a> must match can be passed."],
        [3, "GetNearObjects", "", "Returns a table of <a class=\"mod\" href=\"WorldObject/index.html\">WorldObject</a>s in sight of the <a class=\"mod\" href=\"WorldObject/index.html\">WorldObject</a>. The distance, type, entry and hostility requirements the <a class=\"mod\" href=\"WorldObject/index.html\">WorldObject</a> must match can be passed."],
        [3, "GetNearestCreature", "", "Returns the nearest <a class=\"mod\" href=\"Creature/index.html\">Creature</a> object in sight of the <a class=\"mod\" href=\"WorldObject/index.html\">WorldObject</a> or within the given range and/or with a specific entry ID"],
        [3, "GetNearestGameObject", "", "Returns the nearest <a class=\"mod\" href=\"GameObject/index.html\">GameObject</a> object in sight of the <a class=\"mod\" href=\"WorldObject/index.html\">WorldObject</a> or within the given range and/or with a specific entry ID"],
        [3, "GetNearestPlayer", "", "Returns the nearest <a class=\"mod\" href=\"Player/index.html\">Player</a> object in sight of the <a class=\"mod\" href=\"WorldObject/index.html\">WorldObject</a> or within the given range"],
        [3, "GetO", "", "Returns the current orientation of the <a class=\"mod\" href=\"WorldObject/index.html\">WorldObject</a>"],
        [3, "GetPhaseMask", "", "Returns the current phase of the <a class=\"mod\" href=\"WorldObject/index.html\">WorldObject</a>"],
        [3, "GetPlayersInRange", "", "Returns a table of <a class=\"mod\" href=\"Player/index.html\">Player</a> objects in sight of the <a class=\"mod\" href=\"WorldObject/index.html\">WorldObject</a> or within the given range"],
        [3, "GetRelativePoint", "", "Returns the x, y and z of a point dist away from the <a class=\"mod\" href=\"WorldObject/index.html\">WorldObject</a>."],
        [3, "GetX", "", "Returns the current X coordinate of the <a class=\"mod\" href=\"WorldObject/index.html\">WorldObject</a>"],
        [3, "GetY", "", "Returns the current Y coordinate of the <a class=\"mod\" href=\"WorldObject/index.html\">WorldObject</a>"],
        [3, "GetZ", "", "Returns the current Z coordinate of the <a class=\"mod\" href=\"WorldObject/index.html\">WorldObject</a>"],
        [3, "GetZoneId", "", "Returns the current zone ID of the <a class=\"mod\" href=\"WorldObject/index.html\">WorldObject</a>"],
        [3, "IsWithinLoS", "", "Returns true if the given <a class=\"mod\" href=\"WorldObject/index.html\">WorldObject</a> or coordinates are in the <a class=\"mod\" href=\"WorldObject/index.html\">WorldObject</a>'s line of sight"],
        [3, "RegisterEvent", "", "Registers a timed event to the <a class=\"mod\" href=\"WorldObject/index.html\">WorldObject</a> When the passed function is called, the parameters <code>(eventId, delay, repeats, worldobject)</code> are passed to it. Repeats will decrease on each call if the event does not repeat indefinitely"],
        [3, "RemoveEventById", "", "Removes the timed event from a <a class=\"mod\" href=\"WorldObject/index.html\">WorldObject</a> by the specified event ID"],
        [3, "RemoveEvents", "", "Removes all timed events from a <a class=\"mod\" href=\"WorldObject/index.html\">WorldObject</a>"],
        [3, "SendPacket", "", "Sends a <a class=\"mod\" href=\"WorldPacket/index.html\">WorldPacket</a> to <a class=\"mod\" href=\"Player/index.html\">Player</a>s in sight of the <a class=\"mod\" href=\"WorldObject/index.html\">WorldObject</a>."],
        [3, "SpawnCreature", "", "Spawns the creature at specified location."],
        [3, "SummonGameObject", "", "Spawns a <a class=\"mod\" href=\"GameObject/index.html\">GameObject</a> at specified location."],
    ],
    "paths": []
};searchIndex["WorldPacket"] = {
    "items": [
        [0, "", "WorldPacket", ""],
        [3, "GetOpcode", "", "Returns the opcode of the <a class=\"mod\" href=\"WorldPacket/index.html\">WorldPacket</a>."],
        [3, "GetSize", "", "Returns the size of the <a class=\"mod\" href=\"WorldPacket/index.html\">WorldPacket</a>."],
        [3, "ReadByte", "", "Reads and returns an int8 value from the <a class=\"mod\" href=\"WorldPacket/index.html\">WorldPacket</a>."],
        [3, "ReadDouble", "", "Reads and returns a double value from the <a class=\"mod\" href=\"WorldPacket/index.html\">WorldPacket</a>."],
        [3, "ReadFloat", "", "Reads and returns a float value from the <a class=\"mod\" href=\"WorldPacket/index.html\">WorldPacket</a>."],
        [3, "ReadGUID", "", "Reads and returns a uint64 value from the <a class=\"mod\" href=\"WorldPacket/index.html\">WorldPacket</a>."],
        [3, "ReadLong", "", "Reads and returns an int32 value from the <a class=\"mod\" href=\"WorldPacket/index.html\">WorldPacket</a>."],
        [3, "ReadShort", "", "Reads and returns an int16 value from the <a class=\"mod\" href=\"WorldPacket/index.html\">WorldPacket</a>."],
        [3, "ReadString", "", "Reads and returns a string value from the <a class=\"mod\" href=\"WorldPacket/index.html\">WorldPacket</a>."],
        [3, "ReadUByte", "", "Reads and returns a uint8 value from the <a class=\"mod\" href=\"WorldPacket/index.html\">WorldPacket</a>."],
        [3, "ReadULong", "", "Reads and returns a uint32 value from the <a class=\"mod\" href=\"WorldPacket/index.html\">WorldPacket</a>."],
        [3, "ReadUShort", "", "Reads and returns a uint16 value from the <a class=\"mod\" href=\"WorldPacket/index.html\">WorldPacket</a>."],
        [3, "SetOpcode", "", "Sets the opcode of the <a class=\"mod\" href=\"WorldPacket/index.html\">WorldPacket</a> by specifying an opcode."],
        [3, "WriteByte", "", "Writes an int8 value to the <a class=\"mod\" href=\"WorldPacket/index.html\">WorldPacket</a>."],
        [3, "WriteDouble", "", "Writes a double value to the <a class=\"mod\" href=\"WorldPacket/index.html\">WorldPacket</a>."],
        [3, "WriteFloat", "", "Writes a float value to the <a class=\"mod\" href=\"WorldPacket/index.html\">WorldPacket</a>."],
        [3, "WriteGUID", "", "Writes an uint64 value to the <a class=\"mod\" href=\"WorldPacket/index.html\">WorldPacket</a>."],
        [3, "WriteLong", "", "Writes an int32 value to the <a class=\"mod\" href=\"WorldPacket/index.html\">WorldPacket</a>."],
        [3, "WriteShort", "", "Writes an int16 value to the <a class=\"mod\" href=\"WorldPacket/index.html\">WorldPacket</a>."],
        [3, "WriteString", "", "Writes a string to the <a class=\"mod\" href=\"WorldPacket/index.html\">WorldPacket</a>."],
        [3, "WriteUByte", "", "Writes an uint8 value to the <a class=\"mod\" href=\"WorldPacket/index.html\">WorldPacket</a>."],
        [3, "WriteULong", "", "Writes an uint32 value to the <a class=\"mod\" href=\"WorldPacket/index.html\">WorldPacket</a>."],
        [3, "WriteUShort", "", "Writes an uint16 value to the <a class=\"mod\" href=\"WorldPacket/index.html\">WorldPacket</a>."],
    ],
    "paths": []
};

initSearch(searchIndex);